---
settings:
  name: Element Software
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: SolidFire y el software Element 12.5 y documentación posterior
    url: "/index.html"
  - title: Notas de la versión
    url: "/concepts/concept_rn_relatedrn_element.html"
    entries:
    - title: Novedades
      url: "/concepts/concept_rn_whats_new_element.html"
  - section: concepts
  - title: Requisitos
    url: "/setup/concept_requirements_overview.html"
    entries:
    - title: Requisitos de red
      url: "/storage/concept_prereq_networking.html"
    - title: Configuración de switches para los clústeres que ejecutan el software
        Element
      url: "/storage/concept_prereq_switch_configuration_for_solidfire_clusters.html"
    - title: Requisitos de puerto de red
      url: "/storage/reference_prereq_network_port_requirements.html"
  - section: try
  - section: hardware
  - section: esds
  - section: setup
  - section: storage
  - section: hccstorage
  - section: api
  - title: Gestione el almacenamiento con el plugin de Element para vCenter Server
    url: "/element-plug-in-index.html"
  - title: Supervise el almacenamiento con SolidFire Active IQ de NetApp
    url: "/monitor-storage-active-iq.html"
  - section: mnode
  - section: upgrade
  - title: Versiones anteriores
    url: "/element-earlierversions.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Información general del producto
      url: "/concepts/concept_intro_product_overview.html"
    - title: Notas de la versión
      url: "/concepts/concept_rn_relatedrn_element.html"
    - title: Novedades
      url: "/concepts/concept_rn_whats_new_element.html"
    - title: Requisitos
      url: "/setup/concept_requirements_overview.html"
    - title: Información general de la configuración
      url: "/setup/concept_setup_overview.html"
  - title: Instale y mantenga el hardware
    links:
    - title: Información de hardware H410S y H610S
      url: "/hardware/concept_h410s_h610s_info.html"
    - title: Información sobre hardware de SF-Series
      url: "/hardware/concept_sfseries_info.html"
    - title: Vuelva a la información de la imagen de fábrica
      url: "/hardware/concept_rtfi_configure.html"
    - title: Revisiones de firmware admitidas para los nodos de almacenamiento H-Series
        de NetApp
      url: "/hardware/fw_storage_nodes.html"
  - title: Gestionar el almacenamiento
    links:
    - title: Use la interfaz de usuario del software Element
      url: "/storage/index.html"
    - title: Utilice el control del cloud híbrido de NetApp
      url: "/hccstorage/index.html"
    - title: Utilice la API del software Element
      url: "/api/index.html"
    - title: Use el plugin de Element para vCenter Server
      url: https://docs.netapp.com/us-en/vcp/
    - title: Utilice SolidFire Active IQ de NetApp
      url: https://docs.netapp.com/us-en/solidfire-active-iq/
    - title: Trabaje con el nodo de gestión
      url: "/mnode/task_mnode_work_overview.html"
  - title: Instale y utilice SDS empresarial de SolidFire
    links:
    - title: Descripción general de SolidFire eSDS
      url: "/esds/concept_get_started_esds.html"
    - title: Inicio rápido
      url: https://docs.netapp.com/us-en/element-software/media/SDS_Quick_Start_Guide.pdf
    - title: Requisitos para la instalación
      url: "/esds/concept_esds_prerequisite_tasks.html"
    - title: Gestionar el almacenamiento
      url: "/esds/reference_esds_element_links.html"
    - title: Mantener SolidFire eSDS
      url: "/esds/concept_esds_maintain.html"
  - title: Uso de herramientas de integración (se requiere inicio de sesión)
    links:
    - title: CLI de Element
      url: https://mysupport.netapp.com/site/tools/tool-eula/elem-cli
    - title: Herramientas de Element PowerShell
      url: https://mysupport.netapp.com/site/tools/tool-eula/elem-powershell-tools
    - title: SDK de Element (Java, .NET, Python)
      url: https://mysupport.netapp.com/site/products/all/details/netapphci-solidfire-elementsoftware/tools-tab
    - title: Suite de prueba de la API de SolidFire Postman
      url: https://github.com/solidfire/postman
    - title: Adaptador de replicación de almacenamiento de SolidFire
      url: https://mysupport.netapp.com/site/products/all/details/elementsra/downloads-tab
    - title: SolidFire Vro
      url: https://mysupport.netapp.com/site/products/all/details/solidfire-vro/downloads-tab
    - title: Proveedor VSS de SolidFire
      url: https://mysupport.netapp.com/site/products/all/details/solidfire-vss-provider/downloads-tab
  - title: NetApp
    links:
    - title: Recursos de SolidFire
      url: https://www.netapp.com/data-storage/solidfire/documentation/
    - title: Soluciones NetApp
      url: https://docs.netapp.com/us-en/netapp-solutions/index.html
  - title: Demostraciones y tutoriales
    links:
    - title: Formación en SolidFire de NetApp University (se requiere inicio de sesión)
      url: https://netapp.sabacloud.com/Saba/Web_spf/NA1PRD0047/common/searchresults/solidfire/LEARNINGEVENT%2COFFERINGTEMPLATE%2CCERTIFICATION%2CCURRICULUM%2COFFERING%2CPACKAGE
    - title: Cómo instalar y escalar su clúster SolidFire de NetApp (vídeo)
      url: http://tv.netapp.com/detail/video/5778540099001?autoStart=true&page=1&q=solidfire
    - title: Instalación de SolidFire de NetApp (vídeo)
      url: https://youtu.be/YKGK5nNSL68
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/AFF-NVMe-EF-Series-and-SolidFire-Discussions/bd-p/flash-storage-systems-discussions
    - title: Dónde obtener ayuda
      url: https://mysupport.netapp.com/site/products/all/details/element-software/guideme-tab
  - title: Versiones anteriores
    links:
    - title: Documentación de Element 12.3.x.
      url: https://docs.netapp.com/us-en/element-software-123/index.html
    - title: Documentación de Element 12.2.1
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63945&language=en-US
    - title: Documentación de Element 12.2
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63593&language=en-US
    - title: Documentación de Element 12.0.1
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63946&language=en-US
    - title: Documentación de Element 12.0
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63368&language=en-US
    - title: Element 11.8.2 y documentación anterior
      url: "/element-earlierversions.html"
