---
permalink: hardware/task_sfseries_psurepl.html 
sidebar: sidebar 
keywords: solidfire chassis, power supply replacement, sf-series nodes 
summary: Cada chasis SolidFire incluye dos unidades de suministro de alimentación para redundancia de alimentación. Si falla una unidad de fuente de alimentación, debe sustituirla Lo antes posible. para garantizar que el chasis tiene una fuente de alimentación redundante. 
---
= Sustituya una unidad de fuente de alimentación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada chasis SolidFire incluye dos unidades de suministro de alimentación para redundancia de alimentación. Si falla una unidad de fuente de alimentación, debe sustituirla Lo antes posible. para garantizar que el chasis tiene una fuente de alimentación redundante.

.Lo que necesitará
* Ha determinado que es necesario sustituir la unidad de alimentación.
* Tiene una unidad de suministro de alimentación de repuesto.
* Ha comprobado que la segunda unidad de alimentación está en funcionamiento.
* Usted tiene una muñequera de descarga electrostática (ESD), o usted ha tomado otras precauciones antiestáticas.


.Acerca de esta tarea
Las instrucciones se aplican si dispone de un chasis de unidad de rack individual (1U) con cualquiera de los siguientes nodos:

* SF2405
* SF4805
* SF9605
* SF9608
* SF19210
* SF38410
* SF-FCN-01
* FC0025


[NOTE]
====
Según la versión del software Element, no se admiten los siguientes nodos:

* A partir de Element 12,8, SF4805, SF9605, SF19210 y SF38410 nodos de almacenamiento.
* A partir de Element 12,7, nodos de almacenamiento SF2405 y SF9608, y nodos FC de FC0025 y SF-FCN-01.
* A partir de los nodos de almacenamiento Element 12.0, SF3010, SF6010 y SF9010.


====
.Pasos
. Desconecte el cable de alimentación de la unidad de alimentación que va a sustituir.
. Pulse el botón de liberación para extraer la unidad de alimentación del chasis.
+

IMPORTANT: Asegúrese de utilizar ambas manos para soportar el peso de la unidad de alimentación.

. Con ambas manos, alinee los bordes de la unidad de alimentación de repuesto con la abertura del chasis y empuje suavemente la unidad hacia dentro del chasis.
+

IMPORTANT: No ejerza demasiada fuerza al deslizar la unidad de alimentación en el chasis para evitar daños en el hardware.

. Enchufe el cable de alimentación.
. Devuelva la unidad con el error a NetApp siguiendo las instrucciones de la caja que se le envió.
+
Puede ponerse en contacto con el soporte de NetApp para obtener ayuda sobre el procedimiento de sustitución.





== Obtenga más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

