---
sidebar: sidebar 
permalink: mnode/task_mnode_add_assets.html 
summary: Es posible añadir un activo de controladora a la configuración del nodo de gestión mediante la interfaz de usuario de API DE REST. 
keywords: netapp, mnode, management node, rest api, Element 
---
= Añada un activo de controladora al nodo de gestión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Es posible añadir un activo de controladora a la configuración del nodo de gestión mediante la interfaz de usuario de API DE REST.

Es posible que tenga que agregar un activo si ha escalado recientemente su instalación y no se han añadido automáticamente nuevos activos a la configuración. Utilice estas API para añadir activos que se han añadido recientemente a su instalación.

.Lo que necesitará
* La versión del clúster ejecuta el software NetApp Element 11.3 o una versión posterior.
* Un nodo de gestión se implementó con la versión 11.3 o posterior.
* Se creó un nuevo rol HCC de NetApp en vCenter para limitar la vista de servicios de nodos de gestión a activos de solo NetApp. Consulte link:task_mnode_create_netapp_hcc_role_vcenter.html["Cree una función HCC de NetApp en vCenter"]


.Pasos
. Obtenga el ID de activo base para la instalación:
+
.. Abra la interfaz de usuario de la API DE REST del servicio de inventario en el nodo de gestión:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Seleccione *autorizar* y complete lo siguiente:
+
... Introduzca el nombre de usuario y la contraseña del clúster.
... Introduzca el ID de cliente as `mnode-client`.
... Seleccione *autorizar* para iniciar una sesión.
... Cierre la ventana.


.. En la interfaz de usuario DE LA API DE REST, seleccione *GET ​/Installations*.
.. Seleccione *probar*.
.. Seleccione *Ejecutar*.
.. Del cuerpo de respuesta del código 200, copie el `id` para la instalación.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: Su instalación tiene una configuración de activos base que se creó durante la instalación o la actualización.

.. En la interfaz de usuario DE LA API DE REST, seleccione *GET /Installations/{id}*.
.. Seleccione *probar*.
.. Pegue el ID de activo de instalación en el campo *id*.
.. Seleccione *Ejecutar*.
.. En la respuesta, copie y guarde el ID de controladora del clúster (`"controllerId"`) para usar en un paso posterior.


. Para añadir un subactivo de controladora a un activo base existente, seleccione:
+
[listing]
----
POST /assets/{asset_id}/controllers
----
+
.. Abra la interfaz de usuario de API DE REST de mNode Service en el nodo de gestión:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Seleccione *autorizar* y complete lo siguiente:
+
... Introduzca el nombre de usuario y la contraseña del clúster.
... Introduzca el ID de cliente as `mnode-client`.
... Seleccione *autorizar* para iniciar una sesión.
... Cierre la ventana.


.. Seleccione *POST /Asset/{Asset_id}/controllers*.
.. Seleccione *probar*.
.. Introduzca el ID de activo base principal en el campo *Asset_id*.
.. Añada los valores necesarios a la carga útil.
.. Seleccione *Ejecutar*.




[discrete]
== Obtenga más información

* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]

