---
permalink: concepts/concept_solidfire_concepts_data_protection.html 
sidebar: sidebar 
keywords: what is, element, solidfire, replication, clone, snapshot, protection domain, double helix 
summary: Las funcionalidades de protección de datos incluyen replicación remota, snapshots de volúmenes, clonado de volúmenes, Protection Domains y alta disponibilidad con la tecnología Double Helix. 
---
= Protección de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las funcionalidades de protección de datos incluyen replicación remota, snapshots de volúmenes, clonado de volúmenes, Protection Domains y alta disponibilidad con la tecnología Double Helix.

La protección de datos de almacenamiento de Element incluye los siguientes conceptos:

* <<Tipos de replicación remota>>
* <<Snapshots de volumen para proteger los datos>>
* <<Clones de volúmenes>>
* <<Información general del proceso de backup y restauración para el almacenamiento Element>>
* <<Dominios de protección>>
* <<custom_pd,Dominios de protección personalizados>>
* <<Alta disponibilidad de Double Helix>>




== Tipos de replicación remota

La replicación remota de datos puede adoptar las siguientes formas:

* <<Replicación síncrona y asíncrona entre clústeres>>
* <<Replicación solo de Snapshot>>
* <<Replicación entre clústeres de Element y ONTAP mediante SnapMirror>>


Para obtener más información, consulte https://www.netapp.com/pdf.html?item=/media/10607-tr4741pdf.pdf["TR-4741: Replicación remota del software NetApp Element"^].



=== Replicación síncrona y asíncrona entre clústeres

En los clústeres que ejecutan el software NetApp Element, la replicación en tiempo real permite la creación rápida de copias remotas de datos de volumen.

Un clúster de almacenamiento se puede emparejar con hasta otros cuatro clústeres de almacenamiento. Es posible replicar datos de volúmenes de forma síncrona o asíncrona desde un clúster de una pareja de clústeres para escenarios de conmutación por error y conmutación tras recuperación.



==== Replicación síncrona

La replicación síncrona replica continuamente datos del clúster de origen al clúster de destino y se ve afectada por la latencia, la pérdida de paquetes, la fluctuación y el ancho de banda.

La replicación síncrona es adecuada para las siguientes situaciones:

* Replicación de varios sistemas a corta distancia
* Sitio de recuperación ante desastres que sea geográficamente local en el origen
* Las aplicaciones más urgentes y la protección de las bases de datos
* Aplicaciones de continuidad del negocio que requieren que el sitio secundario actúe como el sitio principal cuando el sitio principal esté inactivo




==== Replicación asíncrona

La replicación asíncrona replica continuamente datos de un clúster de origen a un clúster de destino sin esperar los reconocimientos del clúster de destino. Durante la replicación asíncrona, las escrituras se reconocen en el cliente (aplicación) después de que se aplican en el clúster de origen.

La replicación asíncrona es apropiada para las siguientes situaciones:

* El sitio de recuperación ante desastres está lejos del origen y la aplicación no tolera latencias inducidas por la red.
* La red que conecta los clústeres de origen y destino tiene limitaciones de ancho de banda.




=== Replicación solo de Snapshot

La protección de datos con Snapshot replica los datos modificados en momentos específicos a un clúster remoto. Solo se replican las copias de Snapshot que se crean en el clúster de origen. No se producen las escrituras activas del volumen de origen.

Puede establecer la frecuencia de las replicaciones de snapshots.

La replicación Snapshot no afecta a la replicación asíncrona o síncrona.



=== Replicación entre clústeres de Element y ONTAP mediante SnapMirror

Con la tecnología SnapMirror de NetApp, puede replicar copias snapshot realizadas mediante el software NetApp Element en ONTAP con fines de recuperación ante desastres. En una relación de SnapMirror, Element es un extremo y ONTAP es el otro.

SnapMirror es la tecnología de replicación Snapshot de NetApp que facilita la recuperación ante desastres, diseñada para la conmutación por error del almacenamiento principal al almacenamiento secundario en un centro geográficamente remoto. La tecnología SnapMirror crea una réplica, o réplica, de los datos del trabajo en almacenamiento secundario desde el cual puede seguir proporcionando datos si se produce una interrupción del servicio en el sitio principal. Los datos se reflejan en el nivel de volumen.

La relación entre el volumen de origen en el almacenamiento primario y el volumen de destino en el almacenamiento secundario se denomina relación de protección de datos. Los clústeres se denominan extremos en los que residen los volúmenes y los volúmenes que contienen los datos replicados deben tener una relación entre iguales. Una relación entre iguales permite que clústeres y volúmenes intercambien datos de forma segura.

SnapMirror se ejecuta de forma nativa en las controladoras ONTAP de NetApp y está integrado en Element, que se ejecuta en clústeres de NetApp HCI y SolidFire. La lógica para controlar SnapMirror reside en el software ONTAP; por tanto, todas las relaciones de SnapMirror deben implicar al menos un sistema ONTAP para realizar las tareas de coordinación. Los usuarios gestionan las relaciones entre los clústeres de Element y ONTAP principalmente mediante la interfaz de usuario de Element; no obstante, algunas tareas de gestión residen en ONTAP System Manager de NetApp. Los usuarios también pueden gestionar SnapMirror mediante la CLI y la API, que están disponibles en ONTAP y Element.

Consulte https://fieldportal.netapp.com/content/616239["TR-4651: Arquitectura y configuración de SnapMirror para SolidFire de NetApp"^] (se requiere inicio de sesión)

Es necesario habilitar manualmente la funcionalidad SnapMirror en el nivel de clúster mediante el software Element. La funcionalidad SnapMirror está deshabilitada de forma predeterminada y no se habilita automáticamente como parte de una nueva instalación o actualización.

Después de habilitar SnapMirror, es posible crear relaciones de SnapMirror desde la pestaña Data Protection del software Element.

El software NetApp Element 10.1 y versiones posteriores admite la funcionalidad de SnapMirror para copiar y restaurar copias Snapshot con sistemas ONTAP.

Los sistemas que ejecutan Element 10.1 y versiones posteriores incluyen el código que puede comunicarse directamente con SnapMirror en sistemas ONTAP que ejecutan 9.3 o posterior. La API de Element proporciona métodos para habilitar la funcionalidad de SnapMirror en clústeres, volúmenes y copias de Snapshot. Además, la interfaz de usuario de Element incluye la funcionalidad para gestionar las relaciones de SnapMirror entre el software Element y los sistemas ONTAP.

A partir de los sistemas Element 10.3 y ONTAP 9.4, es posible replicar volúmenes originados por ONTAP en volúmenes de Element en casos de uso específicos con funcionalidad limitada.

Para obtener más información, consulte la documentación de ONTAP.



== Snapshots de volumen para proteger los datos

Una copia de Snapshot de volumen es una copia de un momento específico de un volumen que se puede utilizar más adelante para restaurar un volumen a ese momento específico.

Aunque las copias de Snapshot son similares a los clones de volúmenes, las copias de Snapshot son réplicas de los metadatos del volumen, por lo que no se pueden montar ni escribir en ellas. Además, para crear una copia de Snapshot de volumen, solo se requiere una pequeña cantidad de espacio y recursos del sistema, lo cual es más rápido crear una copia de Snapshot que clonar.

Las snapshots se pueden replicar en un clúster de remoto y usarlas como copia de backup del volumen. Gracias a ello, es posible revertir un volumen a un momento específico mediante la copia de Snapshot replicada, así como crear un clon de un volumen a partir de esta copia de Snapshot replicada.

Es posible realizar backups de copias de Snapshot de un clúster de Element en un almacén de objetos externo o en otro clúster de Element. Cuando se crea un backup de una copia de Snapshot en un almacén de objetos externo, debe haber una conexión con el almacén de objetos que permita realizar operaciones de lectura y escritura.

Es posible realizar una copia Snapshot de un volumen individual o varias para la protección de datos.



== Clones de volúmenes

Un clon de un solo volumen o de varios volúmenes es una copia puntual de los datos. Cuando se clona un volumen, el sistema crea una copia de Snapshot del volumen y, a continuación, crea una copia de los datos que se indican en la copia de Snapshot.

Este es un proceso asíncrono, y la cantidad de tiempo que requiere el proceso depende del tamaño del volumen que se clona y de la carga del clúster actual.

El clúster admite hasta dos solicitudes de clones en ejecución por volumen a la vez y hasta ocho operaciones de clones de volúmenes activos a la vez. Las solicitudes que superen este límite se pondrán en cola para procesarlas más adelante.



== Información general del proceso de backup y restauración para el almacenamiento Element

Es posible realizar backups y restaurar volúmenes en otro almacenamiento de SolidFire, así como en almacenes de objetos secundarios que sean compatibles con OpenStack Swift o Amazon S3.

Es posible realizar un backup de un volumen en los siguientes casos:

* Un clúster de almacenamiento de SolidFire
* Un almacén de objetos Amazon S3
* Un almacén de objetos OpenStack Swift


Cuando se restauran volúmenes desde OpenStack Swift o Amazon S3, se necesita información de manifiesto desde el proceso de backup original. Si desea restaurar un volumen de del cual se había realizado un backup en un sistema de almacenamiento de SolidFire, no será necesaria ninguna información de manifiesto.



== Dominios de protección

Un dominio de protección es un nodo o un conjunto de nodos agrupados, de modo que cualquier parte o incluso todos fallen, al tiempo que se mantiene la disponibilidad de los datos. Los dominios de protección permiten que un clúster de almacenamiento se repare automáticamente de la pérdida de un chasis (afinidad de chasis) o de todo un dominio (grupo de chasis).

Es posible habilitar manualmente la supervisión de dominios de protección mediante el punto de extensión NetApp Element Configuration en el plugin de NetApp Element para vCenter Server. Puede seleccionar un umbral para Protection Domain a partir de dominios de nodo o de chasis. También es posible habilitar la supervisión de Protection Domain mediante la API o la interfaz de usuario web de Element.

Un diseño de Protection Domain asigna cada nodo a un dominio de protección específico.

Se admiten dos diseños diferentes de Protection Domain, denominados niveles de Protection Domain.

* En el nivel de nodo, cada nodo está en su propio dominio de protección.
* En el nivel del chasis, solo los nodos que comparten un chasis se encuentran en el mismo dominio de protección.
+
** La distribución del nivel de chasis se determina automáticamente desde el hardware cuando el nodo se añade al clúster.
** En un clúster en el que cada nodo se encuentra en un chasis independiente, estos dos niveles son funcionalmente idénticos.




Cuando crea un clúster nuevo, si utiliza nodos de almacenamiento que residen en un chasis compartido, puede que desee considerar diseñar la protección contra fallos en el nivel del chasis mediante la función Protection Domains.



== [[custom_pd]]Dominios de protección personalizados

Puede definir un diseño personalizado de Protection Domain que coincida con el diseño de nodo y chasis específicos, y donde cada nodo está asociado a un y solo un dominio de protección personalizado. De manera predeterminada, cada nodo se asigna al mismo dominio de protección personalizado predeterminado.

Si no se asignan dominios de protección personalizados:

* El funcionamiento del clúster no se ve afectado.
* El nivel personalizado no es tolerante ni resiliente.


Cuando se configuran los dominios de protección personalizados de un clúster, se pueden ver tres niveles posibles de protección en la consola de la interfaz de usuario web de Element:

* No protegido: El clúster de almacenamiento no está protegido ante el fallo de uno de sus dominios de protección personalizados. Para solucionarlo, añada más capacidad de almacenamiento al clúster o vuelva a configurar los dominios de protección personalizados del clúster para proteger el clúster de una posible pérdida de datos.
* Tolerancia a fallos: El clúster de almacenamiento tiene suficiente capacidad libre para evitar la pérdida de datos tras el fallo de uno de sus dominios de protección personalizados.
* Fault resiliente: El clúster de almacenamiento tiene suficiente capacidad libre para recuperarse tras el fallo de uno de sus dominios de protección personalizados. Una vez completado el proceso de reparación, el clúster se protegerá de la pérdida de datos si otros dominios fallan.


Si se asigna más de un dominio de protección personalizado, cada subsistema asignará duplicados a dominios de protección personalizados separados. Si esto no es posible, se revierte a la asignación de duplicados a nodos separados. Cada subsistema (por ejemplo, bandejas, segmentos, proveedores de extremo de protocolo y conjunto) realiza esto de forma independiente.

Es posible usar la interfaz de usuario de Element a. link:../storage/task_data_protection_configure_custom_protection_domains.html["Configure los dominios de protección personalizados"]O puede utilizar los siguientes métodos API:

* link:../api/reference_element_api_getprotectiondomainlayout.html["GetProtectionDomainLayout"] - Muestra en qué chasis y en qué dominio de protección personalizado se encuentra cada nodo.
* link:../api/reference_element_api_setprotectiondomainlayout.html["SetProtectionDomainLayout"] - Permite asignar un dominio de protección personalizado a cada nodo.




== Alta disponibilidad de Double Helix

La protección de datos de Double Helix es un método de replicación que expande al menos dos copias de datos redundantes en todas las unidades de un sistema. El enfoque “sin RAID” permite que un sistema absorba múltiples fallos simultáneos en todos los niveles del sistema de almacenamiento y los repare rápidamente.
