---
permalink: concepts/reference_solidfire_element_ug_where_to_find_additional_information.html 
sidebar: sidebar 
keywords:  
summary: Puede obtener más información acerca de las tareas relacionadas con el sistema de almacenamiento de SolidFire en el centro de documentación de SolidFire de NetApp y en los recursos disponibles en la página NetApp SolidFire Resources. 
---
= Dónde encontrar información adicional
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede obtener más información acerca de las tareas relacionadas con el sistema de almacenamiento de SolidFire en el centro de documentación de SolidFire de NetApp y en los recursos disponibles en la página NetApp SolidFire Resources.

En el centro de documentación, también puede encontrar información sobre la instalación y el mantenimiento del hardware, los recursos de contenido adicionales disponibles, los enlaces a problemas conocidos y resueltos, y las notas de la versión más recientes.

* *Página de recursos de SolidFire de NetApp*
+
Proporciona recursos sobre el software Element, incluidos enlaces a contenido de vídeo e informes técnicos.

+
https://www.netapp.com/us/documentation/solidfire.aspx["Recursos de almacenamiento All-Flash de SolidFire"]

* *Centro de documentación de SolidFire* de NetApp
+
Proporciona información sobre la instalación y el mantenimiento del hardware, recursos de contenido adicionales disponibles, enlaces a problemas conocidos y resueltos, y las notas de la versión más recientes.

+
https://docs.netapp.com/sfe-113/index.jsp["Centro de documentación de SolidFire y Element 11.3"]

* *https://kb.netapp.com/app/answers/answer_view/a_id/1000941/loc/en_US[NetApp elementos de SolidFire problemas conocidos]*
+
Proporciona una lista de problemas conocidos en las versiones actual y anteriores del software Element.

* *https://kb.netapp.com/app/answers/answer_view/a_id/1000933[NetApp problemas resueltos de elemento SolidFire]*
+
Proporciona una lista de problemas resueltos en las versiones actuales y anteriores del software Element.


