---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: Las redes virtuales del almacenamiento de SolidFire permiten que el tráfico entre varios clientes en redes lógicas independientes se conecten a un clúster. Las conexiones al clúster se separan en la pila de redes mediante el etiquetado de VLAN. 
---
= Gestionar redes virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las redes virtuales del almacenamiento de SolidFire permiten que el tráfico entre varios clientes en redes lógicas independientes se conecten a un clúster. Las conexiones al clúster se separan en la pila de redes mediante el etiquetado de VLAN.



== Obtenga más información

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Añadir una red virtual]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Habilite el enrutamiento y el reenvío virtuales]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Editar una red virtual]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[Edite las VLAN de VRF]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Eliminar una red virtual]

