---
permalink: storage/concept-element-replication-create-custom-replication-policy.html 
sidebar: sidebar 
keywords: ontap, cli, create, custom, replication, policy, relationship, 
summary: Puede crear una directiva de replicación personalizada si la directiva predeterminada para una relación no es adecuada. 
---
= Cree una política de replicación personalizada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar una directiva predeterminada o personalizada al crear una relación de replicación. Para una política de replicación unificada personalizada, debe definir una o más _rules_ que determinen qué copias de snapshot se transfieren durante la inicialización y actualización.

Puede crear una directiva de replicación personalizada si la directiva predeterminada para una relación no es adecuada. Se pueden comprimir datos en una transferencia de red, por ejemplo, o modificar el número de intentos que realiza SnapMirror para transferir copias Snapshot.

.Acerca de esta tarea
El _policy type_ de la directiva de replicación determina el tipo de relación que admite. En la siguiente tabla se muestran los tipos de directivas disponibles.

[cols="2*"]
|===


| Tipo de política | Tipo de relación 


 a| 
reflejo asíncrono
 a| 
Recuperación ante desastres de SnapMirror



 a| 
mirror-vault
 a| 
Replicación unificada

|===
.Paso
. Cree una política de replicación personalizada:
+
`snapmirror policy create -vserver _SVM_ -policy policy -type async-mirror|mirror-vault -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
A partir de ONTAP 9.5, puede especificar la programación para crear una programación de copias Snapshot común para las relaciones de SnapMirror síncronas mediante `-common-snapshot-schedule` el parámetro. De forma predeterminada, la programación común de copias de Snapshot para las relaciones síncronas de SnapMirror es de una hora. Es posible especificar un valor entre 30 minutos y dos horas para la programación de copia Snapshot para las relaciones síncronas de SnapMirror.

+
En el ejemplo siguiente se crea una política de replicación personalizada para la recuperación ante desastres de SnapMirror que permite la compresión de red para las transferencias de datos:

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
En el ejemplo siguiente se crea una política de replicación personalizada para la replicación unificada:

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


.Después de terminar
Para los tipos de políticas «marror-vault», debe definir reglas que determinen qué copias de instantáneas se transfieren durante la inicialización y actualización.

Utilice `snapmirror policy show` el comando para verificar que la política de SnapMirror se ha creado. Para obtener una sintaxis de comando completa, consulte la página man.
