---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: 'La gestión de claves externas \(EKM\) proporciona una gestión de claves de autenticación segura \(AK\) junto con un servidor de claves externo fuera de clúster \(EKS\). El AKS se utiliza para bloquear y desbloquear unidades de autocifrado (SED) cuando se habilita el cifrado en reposo en el clúster.' 
---
= Comience con la gestión de claves externas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La gestión de claves externas (EKM) ofrece gestión de claves de autenticación seguras (AK) en combinación con un servidor de claves externo (EKS) fuera de clúster. El AKS se utiliza para bloquear y desbloquear unidades de cifrado automático (SED) cuando link:../concepts/concept_solidfire_concepts_security.html["cifrado en reposo"] está habilitado en el clúster. El EKS proporciona una generación y almacenamiento seguros del AKS. El clúster utiliza el protocolo de interoperabilidad de gestión de claves (KMIP, en inglés "Key Management Interoperability Protocol"), un protocolo estándar definido de OASIS para comunicarse con el EKS.


NOTE: Solo el cifrado de software en reposo está disponible para los clústeres SDS empresariales de SolidFire.

* link:task_system_manage_key_set_up_external_key_management.html["Configurar la administración externa"]
* link:task_system_manage_rekey_software_ear_master_key.html["Vuelva a obtener el cifrado de software en la clave maestra de REST"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["Recuperación de claves de autenticación no válidas o inaccesibles"]
* link:concept_system_manage_key_external_key_management_api_commands.html["Comandos de API de gestión de claves externas"]


[discrete]
== Obtenga más información

* link:../api/reference_element_api_createcluster.html["CreateCluster API que se puede usar para habilitar el cifrado de software en reposo"]
* https://www.netapp.com/data-storage/solidfire/documentation/["Página de recursos de SolidFire de NetApp"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

