---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: 'Es posible gestionar los datos en un clúster que ejecuta el software Element desde la pestaña Management de la interfaz de usuario de Element. Las funciones de gestión de clúster disponibles incluyen la creación y la gestión de volúmenes de datos, cuentas de usuario, grupos de acceso de volúmenes, iniciadores y políticas de calidad de servicio \(QoS\).' 
---
= Gestione volúmenes y volúmenes virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible gestionar los datos en un clúster que ejecuta el software Element desde la pestaña Management de la interfaz de usuario de Element. Las funciones de gestión de clúster disponibles incluyen la creación y la gestión de volúmenes de datos, grupos de acceso de volúmenes, iniciadores y políticas de calidad de servicio (QoS).

* link:task_data_manage_volumes_work_with_volumes_task.html["Trabaje con volúmenes"]
* link:concept_data_manage_vvol_work_virtual_volumes.html["Trabaje con volúmenes virtuales"]
* link:concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html["Trabajar con iniciadores y grupos de acceso de volúmenes"]




== Si quiere más información

* https://www.netapp.com/data-storage/solidfire/documentation["Página SolidFire y Element Resources"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

