---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: 'Es posible gestionar los datos en un clúster que ejecuta el software Element desde la pestaña Management de la interfaz de usuario de Element. Las funciones de gestión de clúster disponibles incluyen la creación y la gestión de volúmenes de datos, cuentas de usuario, grupos de acceso de volúmenes, iniciadores y políticas de calidad de servicio \(QoS\).' 
---
= Aprenda sobre la gestión de volúmenes y volúmenes virtuales.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible gestionar los datos en un clúster que ejecuta el software Element desde la pestaña Management de la interfaz de usuario de Element. Las funciones de gestión de clúster disponibles incluyen la creación y la gestión de volúmenes de datos, grupos de acceso de volúmenes, iniciadores y políticas de calidad de servicio (QoS).



[[work-with-volumes]]
== Trabaje con volúmenes

El sistema SolidFire aprovisiona el almacenamiento mediante volúmenes. Los volúmenes son dispositivos de bloque a los que los clientes iSCSI o Fibre Channel acceden a través de la red. En la página Volumes de la pestaña Management, puede crear, modificar, clonar y eliminar volúmenes en un nodo. También puede ver estadísticas sobre el ancho de banda de los volúmenes y el uso de I/O.

link:../storage/concept_data_manage_volumes_quality_of_service_policies.html["Aprenda a trabajar con volúmenes"]



[[work-with-virtual-volumes]]
== Trabaje con volúmenes virtuales

Es posible ver información y realizar tareas en relación con los volúmenes virtuales y sus contenedores de almacenamiento, extremos de protocolo, vinculaciones y hosts asociados mediante la interfaz de usuario de Element.

El sistema de almacenamiento del software NetApp Element se envía con la función Virtual Volumes (VVol) deshabilitada. Debe realizar una tarea puntual que realice la habilitación manual de la funcionalidad VVol de vSphere a través de la interfaz de usuario de Element.

Después de habilitar la funcionalidad VVol, aparecerá una pestaña VVols en la interfaz de usuario de que ofrece opciones de gestión limitada y supervisión relacionadas con VVol. Además, un componente de software del almacenamiento que se conoce como "proveedor VASA" actúa como un servicio de reconocimiento de almacenamiento de vSphere. La mayoría de los comandos de VVol, como la creación, el clonado y la edición de VVol, se inician en un host de vCenter Server o ESXi y se traducen en el proveedor VASA de API de Element para el sistema de almacenamiento del software Element. Los comandos para crear, eliminar y gestionar contenedores de almacenamiento y eliminar volúmenes virtuales se pueden iniciar mediante la interfaz de usuario de Element.

La mayoría de las configuraciones que se necesitan para usar la funcionalidad Virtual Volumes con los sistemas de almacenamiento del software Element se establecen en vSphere. Consulte la guía de configuración de Virtual Volumes de VMware vSphere para el almacenamiento SolidFire_ para registrar el proveedor VASA en vCenter, crear y gestionar almacenes de datos de VVol, y gestionar el almacenamiento en función de políticas.


NOTE: En Element 12.5 y versiones anteriores, no se deben registrar más de un proveedor de VASA de NetApp Element en una sola instancia de vCenter. Cuando se añade un segundo proveedor de VASA NetApp Element, esto hace que no se pueda acceder a todos los almacenes de datos DE VVOL.


NOTE: La compatibilidad CON VASA para varias vCenter está disponible como revisión de actualización si ya se registró un proveedor de VASA en el para vCenter. Para instalar, descargue el archivo VASA39 .tar.gz de https://mysupport.netapp.com/products/element_software/VASA39/index.html["Descargas de software de NetApp"] el sitio y siga las instrucciones en el manifiesto. El proveedor VASA de NetApp Element utiliza un certificado de NetApp. Con este parche, vCenter utiliza el certificado sin modificar para admitir varias instancias de vCenter para que usen VASA y VVol. No modifique el certificado. VASA no admite los certificados SSL personalizados.

link:../storage/task_data_manage_vvol_enable_virtual_volumes.html["Aprenda a trabajar con volúmenes virtuales"]



[[work-with-volume-access-groups-and-initiators]]
== Trabajar con iniciadores y grupos de acceso de volúmenes

Es posible usar iniciadores iSCSI o iniciadores de Fibre Channel para acceder a los volúmenes definidos dentro de los grupos de acceso de volúmenes.

Los grupos de acceso se pueden crear asignando IQN de iniciadores de iSCSI o WWPN de Fibre Channel en una colección de volúmenes. Cada IQN que se añade a un grupo de acceso puede acceder a cada volumen del grupo sin necesidad de contar con autenticación CHAP.

Existen dos tipos de métodos de autenticación CHAP:

* Autenticación CHAP en el nivel de la cuenta: Se puede asignar la autenticación CHAP para la cuenta.
* Autenticación CHAP a nivel de iniciador: Puede asignar secretos y destino CHAP únicos para iniciadores específicos sin estar enlazados a una única cuenta en. Esta autenticación CHAP a nivel de iniciador sustituye las credenciales de nivel de cuenta.


De manera opcional, con CHAP por iniciador, puede aplicar la autorización de iniciador y la autenticación CHAP por iniciador. Estas opciones se pueden definir por iniciador y un grupo de acceso puede contener una combinación de iniciadores con diferentes opciones.

Cada WWPN que se añade a un grupo de acceso habilita el acceso a la red de Fibre Channel a los volúmenes del grupo de acceso.


NOTE: Los grupos de acceso de volúmenes presentan los siguientes límites:

* Se permiten hasta 64 IQN o WWPN en un grupo de acceso.
* Un grupo de acceso puede estar formado por un máximo de 2000 volúmenes.
* Un IQN o un WWPN solo pueden pertenecer a un grupo de acceso.
* Un volumen puede pertenecer a hasta cuatro grupos de acceso.


link:../storage/task_data_manage_vol_access_group_create_a_volume_access_group.html["Aprenda a trabajar con grupos de acceso por volumen e iniciadores."]



[[for-more-information]]
== Si quiere más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

