---
permalink: storage/reference_system_manage_snmp_snmp_details.html 
sidebar: sidebar 
keywords: snmp, overview, reference, mib, settings, trap 
summary: En la página SNMP de la pestaña Cluster, puede ver la siguiente información. 
---
= Obtenga más información sobre SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar el protocolo simple de gestión de redes (SNMP) en el clúster.

Puede seleccionar un solicitante SNMP, seleccionar la versión de SNMP que desea usar, identificar el usuario de modelo de seguridad basado en usuario de SNMP (USM) y configurar las capturas para supervisar el clúster de SolidFire. También permite ver y acceder a los archivos de base de información de gestión.


NOTE: Es posible usar tanto direcciones IPv4 como IPv6.



== Detalles de SNMP

En la página SNMP de la pestaña Cluster, puede ver la siguiente información.

* *MIB SNMP*
+
Los archivos MIB que hay disponibles para que pueda verlos o descargarlos.

* *Configuración general de SNMP*
+
Es posible habilitar o deshabilitar SNMP. Después de habilitar SNMP, puede elegir qué versión quiere usar. Si utiliza la versión 2, puede añadir solicitantes y, si usa la versión 3, puede configurar usuarios USM.

* *Configuración de la captura SNMP*
+
Puede identificar los retos que quiere recibir. Puede establecer el host, el puerto y la cadena de comunidad para cada destinatario de reto.


