---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: 'La página Volume Pairs en la pestaña Data Protection proporciona estos mensajes después de emparejar los volúmenes. Estos mensajes pueden aparecer tanto en los extremos de origen como de destino del par \(a menos que se indique lo contrario\) en la vista de lista Replicating Volumes.' 
---
= Advertencias sobre el emparejamiento de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lapágina Volume Pairs en la pestaña Data Protection proporciona estos mensajes después de emparejar volúmenes. Estos mensajes pueden aparecer tanto en los extremos de origen como de destino de la pareja (a menos que se indique lo contrario) en la vista de lista Replicating Volumes.

* *PausedaClusterFull*
+
Dado que el clúster de destino está lleno, la replicación de origen y la transferencia de datos masivos no pueden continuar. El mensaje aparece solamente en el extremo de origen de la pareja.

* *PausedExceedededededMaxSnapshotCount*
+
El volumen de destino ya cuenta con el número máximo de copias de Snapshot y no puede replicar copias de Snapshot adicionales.

* *PausedManual*
+
El volumen local se pausó manualmente. La pausa se debe cancelar antes de que se reanude la replicación.

* *PausedManualRemote*
+
El volumen remoto se pausó manualmente. Se requiere intervención manual para cancelar la pausa del volumen remoto antes de que se reanude la replicación.

* *PausedMisconfigured*
+
Se esperan un origen y un destino activos. Se requiere intervención manual para reanudar la replicación.

* *PausedQoS*
+
La calidad de servicio de destino no pudo sostener el I/o de entrada. La replicación se reanuda automáticamente. El mensaje aparece solamente en el extremo de origen de la pareja.

* *PausedSlowLink*
+
Se detectó un enlace lento y se detuvo la replicación. La replicación se reanuda automáticamente. El mensaje aparece solamente en el extremo de origen de la pareja.

* *PausedVolumeSizediscordancia*
+
El volumen de destino no tiene el mismo tamaño que el volumen de origen.

* *PausedXCopy*
+
Se envía un comando SCSI XCOPY a un volumen de origen. El comando debe completarse antes de que la replicación se pueda reanudar. El mensaje aparece solamente en el extremo de origen de la pareja.

* *StoppedMisconfigured*
+
Se detectó un error de configuración permanente. El volumen remoto se purgó o se desemparejó. No se puede realizar ninguna acción correctiva y se debe establecer un nuevo emparejamiento.


