---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: Los cifrados SSL son algoritmos de cifrado que utilizan los hosts para establecer una comunicación segura. Hay cifrados estándar que el software Element admite y no estándar cuando esté habilitado el modo FIPS 140-2-2. 
---
= Cifrados SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los cifrados SSL son algoritmos de cifrado que utilizan los hosts para establecer una comunicación segura. Hay cifrados estándar que el software Element admite y no estándar cuando esté habilitado el modo FIPS 140-2-2.

Las siguientes listas proporcionan los cifrados estándar de capa de socket seguro (SSL) que admite el software Element y los cifrados SSL que se admiten cuando el modo FIPS 140-2 está habilitado:

* *FIPS 140-2 desactivado*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A.

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A.

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_IDEA_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_RC4_128_MD5 (RSA 2048) - C.

+
TLS_RSA_WITH_RC4_128_SHA (RSA 2048) - C.

+
TLS_RSA_WITH_SEED_CBC_SHA (RSA 2048) - A.

* *FIPS 140-2 habilitado*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECT571R1) - A.

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A.





== Obtenga más información

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Habilite FIPS 140-2 para HTTPS en el clúster]
