---
permalink: storage/reference_post_deploy_change_default_ssl_certificate.html 
sidebar: sidebar 
keywords: ssl certificate, SSL, private key, self-signed, cluster, nodes, user-defined certificate, API, change default certificate, certificate, Element API 
summary: Puede cambiar el certificado SSL predeterminado y la clave privada del nodo de almacenamiento del clúster mediante la API de NetApp Element. 
---
= Cambie el certificado SSL predeterminado del software Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar el certificado SSL predeterminado y la clave privada del nodo de almacenamiento del clúster mediante la API de NetApp Element.

Cuando se crea un clúster de software de NetApp Element, el clúster crea un certificado único de capa de sockets seguros (SSL) con firma automática y una clave privada que se utiliza para todas las comunicaciones HTTPS a través de la interfaz de usuario de Element, la interfaz de usuario por nodo o las API. El software Element admite certificados autofirmados, así como certificados que una entidad de certificación (CA) de confianza emite y verifica.

Puede utilizar los siguientes métodos API para obtener más información sobre el certificado SSL predeterminado y realizar cambios.

* *GetSSLCertificate*
+
Puede utilizar el link:../api/reference_element_api_getsslcertificate.html["Método GetSSLCertificate"] Para recuperar información acerca del certificado SSL instalado actualmente, incluidos todos los detalles del certificado.

* *SetSSLCertificate*
+
Puede utilizar el link:../api/reference_element_api_setsslcertificate.html["Método SetSSLCertificate"] Para establecer los certificados SSL por clúster y por nodo en el certificado y la clave privada que suministre. El sistema valida el certificado y la clave privada para evitar que se aplique un certificado no válido.

* *RemoveSSLCertificate*
+
La link:../api/reference_element_api_removesslcertificate.html["Método RemoveSSLCertificate"] Quita el certificado SSL y la clave privada instalados actualmente. A continuación, el clúster genera un nuevo certificado autofirmado y una clave privada.




NOTE: El certificado SSL de clúster se aplica automáticamente a todos los nodos nuevos que se añaden al clúster. Cualquier nodo que se quite del clúster se revierte a un certificado autofirmado y toda la información de claves y certificados definidos por el usuario se elimina del nodo.



== Obtenga más información

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["Cambie el certificado SSL predeterminado del nodo de gestión"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["¿Cuáles son los requisitos para configurar certificados SSL personalizados en el software Element?"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

