---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: Es posible añadir varios iniciadores a un grupo de acceso de volúmenes existente para permitir el acceso a volúmenes en el grupo de acceso de volúmenes con o sin necesidad de contar con autenticación CHAP. 
---
= Añada varios iniciadores a un grupo de acceso de volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible añadir varios iniciadores a un grupo de acceso de volúmenes existente para permitir el acceso a volúmenes en el grupo de acceso de volúmenes con o sin necesidad de contar con autenticación CHAP.

Cuando se añaden un iniciador a un grupo de acceso de volúmenes, los iniciadores tienen acceso a todos los volúmenes en ese grupo de acceso de volúmenes.


TIP: Para buscar el iniciador de cada volumen, haga clic en el icono Actions y, a continuación, en *View Details* para el volumen en la lista de volúmenes activos.

Es posible añadir varios iniciadores a un grupo de acceso de volúmenes existente para habilitar el acceso a volúmenes y asignar credenciales CHAP únicas para cada iniciador de ese grupo de acceso de volúmenes. Esto permite aplicar esta opción a los grupos de acceso de volúmenes que ya existen.

Puede asignar atributos CHAP basados en iniciadores mediante una llamada API. Para añadir un nombre de cuenta CHAP y credenciales por iniciador, debe utilizar la llamada API ModifyInitiator para quitar y agregar acceso y atributos de CHAP.

Para obtener más información, consulte link:../api/index.html["Gestione el almacenamiento con la API de Element"].

.Pasos
. Haga clic en *Administración* > *iniciadores*.
. Seleccione los iniciadores que desea añadir a un grupo de acceso.
. Haga clic en el botón *acciones masivas*.
. Haga clic en *Agregar a grupo de acceso de volumen*.
. En el cuadro de diálogo Add to Volume Access Group, seleccione un grupo de acceso en la lista *Volume Access Group*.
. Haga clic en *Agregar*.

