---
permalink: storage/task-element-replication-enable-snapmirror-cluster.html 
sidebar: sidebar 
keywords: ontap, cli, enable, snapmirror, element, cluster 
summary: Es necesario habilitar SnapMirror en el clúster de Element para poder crear una relación de replicación. Solo puede realizar esta tarea en la interfaz de usuario web del software Element o mediante los métodos API. 
---
= Habilite SnapMirror en el clúster de Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es necesario habilitar SnapMirror en el clúster de Element para poder crear una relación de replicación. Solo puede realizar esta tarea en la interfaz de usuario web del software Element o mediante el link:../api/reference_element_api_enablefeature.html["Método API"].

.Antes de empezar
* El clúster de Element debe ejecutar la versión 10.1 o posterior del software NetApp Element.
* Solo se puede habilitar SnapMirror en clústeres de Element que se usan con los volúmenes de ONTAP de NetApp.


.Acerca de esta tarea
El sistema Element viene con SnapMirror deshabilitado de forma predeterminada. SnapMirror no se habilita automáticamente como parte de una nueva instalación o actualización.

[NOTE]
====
Una vez que está habilitada, SnapMirror no se puede deshabilitar. Solo puede deshabilitar la función SnapMirror y restaurar la configuración predeterminada si devuelve el clúster a la imagen de fábrica.

====
.Pasos
. Haga clic en *Clusters* > *Configuración*.
. Busque la configuración específica del clúster para SnapMirror.
. Haga clic en *Activar SnapMirror*.

