---
permalink: storage/task_system_manage_virtual_enable_virtual_routing_and_forwarding.html 
sidebar: sidebar 
keywords: virtual routing, forwarding, enable, vrf, storage networks, create a vlan 
summary: 'Puede habilitar el enrutamiento y el reenvío virtuales \(VRF\), lo que permite que varias instancias de una tabla de enrutamiento existan en un enrutador y funcionen simultáneamente. Dicha funcionalidad solo está disponible para redes de almacenamiento.' 
---
= Habilite el enrutamiento y el reenvío virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar el enrutamiento y el reenvío virtuales (VRF), que permite que varias instancias de una tabla de enrutamiento existan en un enrutador y funcionen simultáneamente. Dicha funcionalidad solo está disponible para redes de almacenamiento.

Solo puede habilitar VRF en el momento de crear una VLAN. Si desea volver a un estado sin VRF, debe eliminar y volver a crear la VLAN.

. Haga clic en *clúster* > *Red*.
. Para habilitar VRF en una VLAN nueva, seleccione *Crear VLAN*.
+
.. Introduzca la información relevante para la nueva VRF/VLAN. Consulte Añadir una red virtual.
.. Active la casilla de verificación *Activar VRF*.
.. *Opcional*: Introduzca una puerta de enlace.


. Haga clic en *Crear VLAN*.




== Obtenga más información

xref:task_system_manage_virtual_add_a_virtual_network.adoc[Añadir una red virtual]
