---
permalink: storage/task-element-replication-initialize-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, initialize, replication, relationship 
summary: 'Para todos los tipos de relaciones, la inicialización realiza una transferencia completa: Realiza una copia Snapshot del volumen de origen y luego transfiere esa copia y todos los bloques de datos a los que hace referencia al volumen de destino.' 
---
= Inicializar una relación de replicación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para todos los tipos de relaciones, la inicialización realiza una transferencia _baseline_: Realiza una copia Snapshot del volumen de origen y luego transfiere esa copia y todos los bloques de datos a los que hace referencia al volumen de destino.

.Antes de empezar
* ONTAP debe haber accesible desde el nodo Element que contiene el volumen que se va a replicar.
* El volumen de Element debe estar habilitado para la replicación de SnapMirror.
* Si está utilizando el tipo de política «marror-vault», se debe haber configurado una etiqueta SnapMirror para que se repliquen las copias Snapshot de Element.
+
[NOTE]
====
Sólo puede realizar esta tarea en el link:concept_snapmirror_labels.html["Interfaz de usuario web del software Element"] o utilizando el link:../api/concept_element_api_snapshots_overview.html["Métodos API"].

====


.Acerca de esta tarea
Debe especificar la ruta de origen del elemento con el formato `<hostip:>/lun/<name>`, donde «`lun`» es la cadena real «`lun`» y `_name_` es el nombre del volumen del elemento.

La inicialización puede requerir mucho tiempo. Puede ser conveniente ejecutar la transferencia básica en horas de menor actividad.

[NOTE]
====
Si la inicialización de una relación desde un origen de ONTAP a un destino de Element genera errores por cualquier motivo, seguirá presentando errores incluso después de haber corregido el problema (un nombre de LUN no válido, por ejemplo). La solución es la siguiente:

. Eliminar la relación.
. Elimine el volumen de destino de Element.
. Cree un nuevo volumen de destino de Element.
. Cree e inicialice una nueva relación desde el origen de ONTAP hasta el volumen de destino de Element.


====
.Paso
. Inicializar una relación de replicación:
+
`snapmirror initialize -source-path <hostip:>/lun/<name> -destination-path <SVM:volume|cluster://SVM/volume>`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el ejemplo siguiente se inicializa la relación entre el volumen de origen `0005` en la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` en `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

