---
permalink: storage/task_snapmirror_use_replication_between_element_and_ontap_clusters.html 
sidebar: sidebar 
keywords: replication, snapmirror, data protection 
summary: Las relaciones de SnapMirror se pueden crear en la pestaña Data Protection de la interfaz de usuario de NetApp Element. La funcionalidad de SnapMirror debe estar habilitada para poder verla en la interfaz de usuario de. 
---
= Use la replicación de SnapMirror entre clústeres de Element y ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las relaciones de SnapMirror se pueden crear en la pestaña Data Protection de la interfaz de usuario de NetApp Element. La funcionalidad de SnapMirror debe estar habilitada para poder verla en la interfaz de usuario de.

IPv6 no es compatible con la replicación de SnapMirror entre el software NetApp Element y los clústeres de ONTAP.

https://www.youtube.com/embed/kerGI1ZtnZQ?rel=0["Vídeo de NetApp: SnapMirror para software NetApp HCI y Element"^]

Los sistemas que ejecutan el software NetApp Element admiten la funcionalidad SnapMirror para copiar y restaurar copias Snapshot con sistemas ONTAP de NetApp. El principal motivo para usar esta tecnología es la recuperación ante desastres de NetApp HCI a ONTAP. Los extremos incluyen ONTAP, ONTAP Select y Cloud Volumes ONTAP. Consulte TR-4641 Protección de datos de NetApp HCI.

http://www.netapp.com/us/media/tr-4641.pdf["Informe técnico de NetApp 4641: Protección de datos de NetApp HCI"^]



== Obtenga más información

* https://www.netapp.com/us/media/tr-4748.pdf["Crear una estructura de datos con NetApp HCI, ONTAP e infraestructura convergente"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-sdbak/home.html["Replicación entre software de NetApp Element y ONTAP"^]

