---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'En cuanto tenga acceso IPMI remoto al nodo, puede cambiar la contraseña predeterminada del administrador de la interfaz de gestión de plataformas inteligentes (IPMI). Puede que desee hacerlo si se han actualizado alguna instalación.' 
---
= Cambie la contraseña de IPMI predeterminada para los nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cuanto tenga acceso IPMI remoto al nodo, puede cambiar la contraseña predeterminada del administrador de la interfaz de gestión de plataformas inteligentes (IPMI). Puede que desee hacerlo si se han actualizado alguna instalación.

Para obtener más información acerca de cómo configurar el acceso IPM para los nodos, consulte link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configure IPMI para cada nodo"^].

Puede cambiar la contraseña de IPM para estos nodos:

* Nodos H410S
* Nodos H610S




== Cambie la contraseña de IPMI predeterminada para los nodos H410S

En cuanto configure el puerto de red IPMI, debe cambiar la contraseña predeterminada de la cuenta de administrador de IPMI en cada nodo de almacenamiento.

.Lo que necesitará
Debe haber configurado la dirección IP de IPMI para cada nodo de almacenamiento.

.Pasos
. Abra un explorador web en un equipo que pueda acceder a la red de IPMI y vaya a la dirección IP de IPMI correspondiente al nodo.
. Introduzca el nombre de usuario `ADMIN` y contraseña `ADMIN` en la solicitud de inicio de sesión de.
. Después de iniciar sesión, haga clic en la ficha *Configuración*.
. Haga clic en *usuarios*.
. Seleccione la `ADMIN` Haga clic en *Modificar usuario*.
. Seleccione la casilla de verificación *Cambiar contraseña*.
. Introduzca una nueva contraseña en los campos *Contraseña* y *Confirmar contraseña*.
. Haga clic en *Modificar* y, a continuación, haga clic en *Aceptar*.
. Repita este procedimiento para todos los demás nodos H410S con contraseñas IPMI predeterminadas.




== Cambie la contraseña de IPMI predeterminada para los nodos H610S

En cuanto configure el puerto de red IPMI, debe cambiar la contraseña predeterminada de la cuenta de administrador de IPMI en cada nodo de almacenamiento.

.Lo que necesitará
Debe haber configurado la dirección IP de IPMI para cada nodo de almacenamiento.

.Pasos
. Abra un explorador web en un equipo que pueda acceder a la red de IPMI y vaya a la dirección IP de IPMI correspondiente al nodo.
. Introduzca el nombre de usuario `root` y contraseña `calvin` en la solicitud de inicio de sesión de.
. Después de iniciar sesión, haga clic en el icono de navegación del menú que aparece en la parte superior izquierda de la página para abrir el cajón de la barra lateral.
. Haga clic en *Configuración*.
. Haga clic en *Administración de usuarios*.
. Seleccione el usuario *Administrador* de la lista.
. Active la casilla de verificación *Cambiar contraseña*.
. Introduzca una nueva contraseña segura en los campos *Contraseña* y *Confirmar contraseña*.
. Haga clic en *Guardar* en la parte inferior de la página.
. Repita este procedimiento para todos los demás nodos H610S con contraseñas de IPMI predeterminadas.




== Obtenga más información

* https://www.netapp.com/data-storage/solidfire/documentation["Página SolidFire y Element Resources"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

