---
permalink: storage/task-element-replication-make-destination-volume-writeable.html 
sidebar: sidebar 
keywords: ontap, cli, make, destination, volume, write 
summary: Debe hacer que el volumen de destino sea editable, para poder proporcionar datos del volumen a los clientes. Puede utilizar el comando snapmirror QUIESCE para detener las transferencias programadas al destino, el comando snapmirror abort para detener las transferencias continuas y el comando snapmirror break para hacer que el destino sea editable. 
---
= Haga que el volumen de destino sea modificable
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando el desastre deshabilita el sitio principal para una relación de recuperación ante desastres de SnapMirror, puede proporcionar datos del volumen de destino con una interrupción mínima. Se puede reactivar el volumen de origen cuando el servicio se restaura en el sitio primario.

Debe hacer que el volumen de destino sea editable, para poder proporcionar datos del volumen a los clientes. Puede utilizar `snapmirror quiesce` el comando para detener las transferencias programadas al destino, `snapmirror abort` el comando para detener las transferencias continuas y el `snapmirror break` comando para que el destino se pueda escribir.

.Acerca de esta tarea
Debe especificar la ruta de origen del elemento con el formato `<hostip:>/lun/<name>`, donde «`lun`» es la cadena real «`lun`» y `name` es el nombre del volumen del elemento.

.Pasos
. Detenga las transferencias programadas al destino:
+
`snapmirror quiesce -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el ejemplo siguiente se detienen las transferencias programadas entre el volumen de origen `0005` en la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` en `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Detenga las transferencias continuas al destino:
+
`snapmirror abort -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el ejemplo siguiente se detienen las transferencias en curso entre el volumen de origen `0005` en la dirección IP 10.0.0.11 y el volumen de destino `volA_dst` `svm_backup` en :

+
[listing]
----
cluster_dst::> snapmirror abort -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Rompa la relación de recuperación ante desastres de SnapMirror:
+
`snapmirror break -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Para obtener una sintaxis de comando completa, consulte la página man.

+
En el ejemplo siguiente, se interrumpe la relación entre el volumen de origen `0005` `volA_dst` en la dirección IP 10.0.0.11 y el volumen de destino en `svm_backup` y el volumen de destino en `volA_dst` `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror break -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

