---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2, cluster, create 
summary: 'La seguridad cada vez resulta más importante para la puesta en marcha de soluciones en muchos entornos de cliente. Los estándares de procesamiento de información federal \(FIPS\) son estándares de seguridad informática e interoperabilidad. El cifrado certificado FIPS 140-2 para datos en reposo es un componente de la solución de seguridad general.' 
---
= Preparar el clúster Element para la función de unidades FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La seguridad cada vez resulta más importante para la puesta en marcha de soluciones en muchos entornos de cliente. Los estándares de procesamiento de información federal (FIPS) son estándares de interoperabilidad y seguridad informática. El cifrado certificado FIPS 140-2 para datos en reposo es un componente de la solución de seguridad general.

Para prepararse para habilitar la función de unidades FIPS, debe evitar combinar nodos donde algunos sean compatibles con unidades FIPS y otros no lo sean.

Un clúster se considera compatible con unidades FIPS según las siguientes condiciones:

* Todas las unidades están certificadas como unidades FIPS.
* Todos los nodos son nodos de unidades FIPS.
* El cifrado en reposo (EAR) está habilitado.
* Se habilitó la función de unidades FIPS. Todas las unidades y los nodos deben ser compatibles con FIPS, y el cifrado en reposo debe habilitarse para habilitar la función de unidad FIPS.

