---
permalink: storage/task_system_manage_cluster_set_the_cluster_full_threshold.html 
sidebar: sidebar 
keywords: cluster fullness, setting threshold, metadata, warning 
summary: Puede cambiar el nivel en el que el sistema genera una advertencia de ocupación de la capacidad del clúster de bloques mediante los pasos siguientes. Además, puede utilizar el método API ModifyClusterFullThreshold para cambiar el nivel en el que el sistema genera una advertencia de bloque o metadatos. 
---
= Establezca el umbral de ocupación del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar el nivel en el que el sistema genera una advertencia de ocupación de la capacidad del clúster de bloques mediante los pasos siguientes. Además, puede utilizar el método API ModifyClusterFullThreshold para cambiar el nivel en el que el sistema genera una advertencia de bloque o metadatos.

.Lo que necesitará
Debe tener privilegios de administrador del clúster.

.Pasos
. Haga clic en *Cluster* > *Settings*.
. En la sección Cluster Full Settings, introduzca un porcentaje en *Raise a warning alert when _% capacity remains before Helix could not recover from a node failure*.
. Haga clic en *Guardar cambios*.




== Obtenga más información

https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/SF_Series/How_are_the_blockSpace_thresholds_calculated_for_Element["Cómo se calculan los umbrales de blockSpace para el elemento"^]
