---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: El sistema SolidFire aprovisiona el almacenamiento mediante volúmenes. Los volúmenes son dispositivos de bloque a los que los clientes iSCSI o Fibre Channel acceden a través de la red. 
---
= Gestione los volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema SolidFire aprovisiona el almacenamiento mediante volúmenes. Los volúmenes son dispositivos de bloque a los que los clientes iSCSI o Fibre Channel acceden a través de la red.

En la página Volumes de la pestaña Management, puede crear, modificar, clonar y eliminar volúmenes en un nodo.



== Cree un volumen

Es posible crear un volumen y asociarlo con una cuenta determinada. Cada volumen debe estar asociado con una cuenta. Gracias a esta asociación, la cuenta podrá acceder al volumen a través de iniciadores iSCSI con las credenciales de CHAP.

Puede especificar la configuración de calidad de servicio de un volumen mientras lo crea.

. Seleccione *Gestión* > *volúmenes*.
. Haga clic en *Crear volumen*.
. En el cuadro de diálogo *Crear un nuevo volumen*, introduzca *Nombre de volumen*.
. Introduzca el tamaño total del volumen.
+

NOTE: El tamaño de volumen predeterminado se selecciona en GB. Los volúmenes se pueden crear con tamaños en GB o GIB:

+
** 1 GB = 1 000 000 000 bytes
** 1 GIB = 1 073 741 824 bytes


. Seleccione *Tamaño de bloque* para el volumen.
. Haga clic en la lista desplegable *cuenta* y seleccione la cuenta que debe tener acceso al volumen.
+
Si no existe ninguna cuenta, haga clic en el enlace *Crear cuenta*, escriba un nuevo nombre de cuenta y haga clic en *Crear*. La cuenta se creará y se asociará con el volumen nuevo.

+

NOTE: Si hay más de 50 cuentas, no aparecerá la lista. Comience a escribir y la función de autocompletar mostrará los posibles valores que puede elegir.

. Para establecer la *calidad del servicio*, realice una de las siguientes acciones:
+
.. En *Directiva*, puede seleccionar una directiva QoS existente, si está disponible.
.. En *Configuración personalizada*, establezca valores mínimos, máximos y de ráfaga personalizados para IOPS o utilice los valores de QoS predeterminados.
+
Los volúmenes que tengan un valor de IOPS máximo o de ráfaga superior a 20 20,000 IOPS podrían requerir una profundidad de cola alta o varias sesiones para alcanzar este nivel de IOPS en un único volumen.



. Haga clic en *Crear volumen*.




== Ver los detalles del volumen

. Seleccione *Gestión* > *volúmenes*.
. Revise los detalles.
+
** *ID*: El ID generado por el sistema para el volumen.
** *Nombre*: El nombre otorgado al volumen cuando fue creado.
** *Cuenta*: El nombre de la cuenta asignada al volumen.
** *Grupos de acceso*: El nombre del grupo o los grupos de acceso de volúmenes a los que pertenece el volumen.
** *Acceso*: Tipo de acceso asignado al volumen cuando se creó. Los posibles valores son los siguientes:
+
*** Read/Write: Se aceptan todas las lecturas y las escrituras.
*** Read Only: Se permite toda la actividad de lectura, pero no la de escritura.
*** Locked: Solo se permite el acceso de administrador.
*** ReplicationTarget: Se designa como un volumen de destino en una pareja de volúmenes replicada.


** *Utilizado*: El porcentaje de espacio utilizado en el volumen.
** *Tamaño*: El tamaño total (en GB) del volumen.
** *ID de nodo primario*: El nodo principal de este volumen.
** *ID de nodo secundario*: La lista de nodos secundarios para este volumen. Pueden ser múltiples valores durante estados transitorios, como el cambio de nodos secundarios, pero normalmente tendrán un único valor.
** *QoS Facelerador*: Identifica si el volumen está acelerando debido a una alta carga en el nodo de almacenamiento principal.
** *Política de QoS*: Nombre y enlace a la política de QoS definida por el usuario.
** *Min IOPS*: El número mínimo de IOPS garantizado para el volumen.
** *Max IOPS*: El número máximo de IOPS permitido para el volumen.
** *Burst IOPS*: El número máximo de IOPS permitido durante un breve período de tiempo para el volumen. El valor predeterminado es de 15 15,000.
** *Instantáneas*: El número de instantáneas creadas para el volumen.
** *Atributos*: Atributos que se han asignado al volumen como par clave/valor mediante un método API.
** *512e*: Indica si 512e está habilitado en un volumen. Los posibles valores son los siguientes:
+
*** Sí
*** No


** *Creado el*: Fecha y hora en que se creó el volumen.






== Ver los detalles de cada volumen

Es posible ver estadísticas de rendimiento de cada volumen.

. Seleccione *Informes* > *rendimiento de volumen*.
. En la lista de volúmenes, haga clic en el icono Actions de un volumen.
. Haga clic en *Ver detalles*.
+
Aparecerá una bandeja en la parte inferior de la página con información general sobre el volumen.

. Para ver información más detallada sobre el volumen, haga clic en *Ver más detalles*.
+
El sistema muestra información detallada y gráficos de rendimiento del volumen.





== Editar los volúmenes activos

Es posible modificar atributos de volúmenes, como los valores de calidad de servicio, el tamaño de los volúmenes y la unidad de medida en la que se calculan los valores de bytes. También se puede modificar el acceso de la cuenta para el uso de la replicación o para restringir el acceso al volumen.

Puede cambiar el tamaño de un volumen cuando haya espacio suficiente en el clúster en las siguientes condiciones:

* Condiciones de funcionamiento normales.
* Se informa de los errores de los volúmenes.
* El volumen se clona.
* El volumen se vuelve a sincronizar.


.Pasos
. Seleccione *Gestión* > *volúmenes*.
. En la ventana *activo*, haga clic en el icono acciones del volumen que desea editar.
. Haga clic en *Editar*.
. *Opcional:* cambie el tamaño total del volumen.
+
** Puede aumentar el tamaño del volumen, pero no reducirlo. En cada operación de ajuste de tamaño, solo se puede ajustar el tamaño de un volumen. Las operaciones de recopilación de datos basura y las actualizaciones de software no interrumpen la operación de cambio de tamaño.
** Si desea ajustar el tamaño del volumen para la replicación, primero debe aumentar el tamaño del volumen asignado como el destino de replicación. Posteriormente, puede cambiar el tamaño del volumen de origen. El tamaño del volumen de destino puede ser mayor o igual que el del volumen de origen, pero no menor.


+
El tamaño de volumen predeterminado se selecciona en GB. Los volúmenes se pueden crear con tamaños en GB o GIB:

+
** 1 GB = 1 000 000 000 bytes
** 1 GIB = 1 073 741 824 bytes


. *Opcional:* Seleccione un nivel de acceso de cuenta diferente de uno de los siguientes:
+
** Solo lectura
** Lectura/Escritura
** Bloqueado
** Destino de replicación


. *Opcional:* Seleccione la cuenta que debería tener acceso al volumen.
+
Si la cuenta no existe, haga clic en el enlace *Crear cuenta*, escriba un nuevo nombre de cuenta y haga clic en *Crear*. La cuenta se creará y se asociará con el volumen.

+

NOTE: Si hay más de 50 cuentas, no aparecerá la lista. Comience a escribir y la función de autocompletar mostrará los posibles valores que puede elegir.

. *Opcional:* para cambiar la selección en *calidad de servicio*, realice una de las siguientes acciones:
+
.. En *Directiva*, puede seleccionar una directiva QoS existente, si está disponible.
.. En *Configuración personalizada*, establezca valores mínimos, máximos y de ráfaga personalizados para IOPS o utilice los valores de QoS predeterminados.
+

NOTE: Si utiliza políticas de calidad de servicio en un volumen, puede establecer la calidad de servicio personalizada para quitar la asociación de la política de calidad de servicio con el volumen. La calidad de servicio personalizada anulará y ajustará los valores de las políticas de calidad de servicio de los volúmenes.

+

TIP: Cuando cambie los valores de IOPS, debe incrementar sus diez o cien. Los valores de entrada deben ser números enteros válidos.

+

TIP: Configure los volúmenes con un valor de ráfaga muy alto. De este modo, el sistema podrá procesar grandes cargas de trabajo secuenciales en bloque ocasionales con mayor rapidez, a la vez que se limitan las IOPS sostenidas de un volumen.



. Haga clic en *Guardar cambios*.




== Eliminar un volumen

Es posible eliminar uno o varios volúmenes de un clúster de almacenamiento de Element.

El sistema no purga de manera inmediata un volumen eliminado, sino que este sigue disponible durante aproximadamente ocho horas. Si un volumen se restaura antes de que el sistema lo purgue, el volumen volverá a conectarse y las conexiones iSCSI se restaurarán.

Si se elimina el volumen que se utilizó para crear una snapshot, sus snapshots asociadas pasan a estar inactivas. Cuando se purgan los volúmenes de origen eliminados, también se eliminan del sistema las snapshots inactivas asociadas.


IMPORTANT: Los volúmenes persistentes asociados con servicios de gestión se crean y se asignan a una nueva cuenta durante la instalación o la actualización. Si utiliza volúmenes persistentes, no modifique o elimine los volúmenes o su cuenta asociada.

.Pasos
. Seleccione *Gestión* > *volúmenes*.
. Para eliminar un solo volumen, realice los siguientes pasos:
+
.. Haga clic en el icono Actions del volumen que desea eliminar.
.. En el menú que se abre, haga clic en *Eliminar*.
.. Confirme la acción.


+
El sistema mueve el volumen al área *borrada* de la página *Volumes*.

. Para eliminar varios volúmenes, realice los siguientes pasos:
+
.. En la lista de volúmenes, active la casilla junto a los volúmenes que quiera eliminar.
.. Haga clic en *acciones masivas*.
.. En el menú que se abre, haga clic en *Eliminar*.
.. Confirme la acción.
+
El sistema mueve los volúmenes al área *Deleted* de la página *Volumes*.







== Restaurar un volumen eliminado

Un volumen se puede restaurar en el sistema si se eliminó, pero aún no se purgó. El sistema purga un volumen de manera automática aproximadamente ocho horas después de que fue eliminado. Si el sistema purgó el volumen, no podrá restaurarlo.

. Seleccione *Gestión* > *volúmenes*.
. Haga clic en la ficha *eliminado* para ver la lista de volúmenes eliminados.
. Haga clic en el icono Actions del volumen que desea restaurar.
. En el menú que se abre, haga clic en *Restaurar*.
. Confirme la acción.
+
El volumen se coloca en la lista *volúmenes activos* y se restauran las conexiones iSCSI con el volumen.





== Purgar un volumen

Cuando se purga un volumen, este se quita de forma permanente del sistema y Se pierden todos los datos del volumen.

El sistema purga de manera automática un volumen eliminado ocho horas después de su eliminación. Sin embargo, si desea purgar un volumen antes de la hora programada, puede hacerlo.

. Seleccione *Gestión* > *volúmenes*.
. Haga clic en el botón *eliminado*.
. Ejecute los pasos para purgar un único volumen o varios volúmenes.
+
[cols="25,75"]
|===
| Opción | Pasos 


 a| 
Purgar un único volumen
 a| 
.. Haga clic en el icono Actions del volumen que desea purgar.
.. Haga clic en *Purgar*.
.. Confirme la acción.




 a| 
Purgar varios volúmenes
 a| 
.. Seleccione los volúmenes que desea purgar.
.. Haga clic en *acciones masivas*.
.. En el menú que se abre, seleccione *Purge*.
.. Confirme la acción.


|===




== Clonar un volumen

Un clon se puede crear de un solo volumen o de varios volúmenes para hacer una copia de los datos en un momento específico. Cuando se clona un volumen, el sistema crea una copia de Snapshot del volumen y, a continuación, crea una copia de los datos que se indican en la copia de Snapshot. Este es un proceso asíncrono, y la cantidad de tiempo que requiere el proceso depende del tamaño del volumen que se clona y de la carga del clúster actual.

El clúster admite hasta dos solicitudes de clones en ejecución por volumen a la vez y hasta ocho operaciones de clones de volúmenes activos a la vez. Las solicitudes que superen este límite se pondrán en cola para procesarlas más adelante.


NOTE: Los sistemas operativos difieren en la forma en que tratan los volúmenes clonados. VMware ESXi tratará un volumen clonado como una copia de volumen o un volumen Snapshot. El volumen será un dispositivo disponible para usar para crear un nuevo almacén de datos. Para obtener más información sobre el montaje de volúmenes de clones y el tratamiento de LUN de copias Snapshot, consulte la documentación de VMware en https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["Montar una copia de almacén de datos VMFS"] y.. https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["Gestión de almacenes de datos VMFS duplicados"].


IMPORTANT: Antes de truncar un volumen clonado mediante el clonado en un tamaño más pequeño, asegúrese de preparar las particiones de manera que se adapten al volumen inferior.

.Pasos
. Seleccione *Gestión* > *volúmenes*.
. Para clonar un solo volumen, realice los siguientes pasos:
+
.. En la lista de volúmenes de la página *activo*, haga clic en el icono acciones del volumen que desea clonar.
.. En el menú que se abre, haga clic en *Clonar*.
.. En la ventana *Clone Volume*, introduzca un nombre de volumen para el volumen recién clonado.
.. Seleccione un tamaño y una medida para el volumen utilizando el cuadro de número *Tamaño de volumen* y la lista.
+

NOTE: El tamaño de volumen predeterminado se selecciona en GB. Los volúmenes se pueden crear con tamaños en GB o GIB:

+
*** 1 GB = 1 000 000 000 bytes
*** 1 GIB = 1 073 741 824 bytes


.. Seleccione el tipo de acceso para el volumen que se acaba de clonar.
.. Seleccione una cuenta para asociarla con el volumen recién clonado en la lista *cuenta*.
+

NOTE: Puede crear una cuenta durante este paso si hace clic en el enlace *Crear cuenta*, escribe un nombre de cuenta y hace clic en *Crear*. El sistema agrega automáticamente la cuenta a la lista *cuenta* después de crearla.



. Para clonar varios volúmenes, realice los siguientes pasos:
+
.. En la lista de volúmenes de la página *Active*, marque la casilla junto a los volúmenes que desee clonar.
.. Haga clic en *acciones masivas*.
.. En el menú que se abre, seleccione *Clonar*.
.. En el cuadro de diálogo *Clonar varios volúmenes*, introduzca un prefijo para los volúmenes clonados en el campo *prefijo de nombre de volumen nuevo*.
.. Seleccione una cuenta para asociarla con los volúmenes clonados en la lista *cuenta*.
.. Seleccione el tipo de acceso de los volúmenes clonados.


. Haga clic en *Iniciar clonación*.
+

NOTE: Al aumentar el tamaño del volumen de un clon, se genera un volumen nuevo con espacio libre adicional al final del volumen. Según cómo use el volumen, podría necesitar ampliar las particiones o crear otras nuevas en el espacio libre para utilizarlo.





== Si quiere más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

