---
permalink: storage/task_snapmirror_enable_on_the_cluster.html 
sidebar: sidebar 
keywords: element, snapmirror, enable, cluster, ui, manually enable 
summary: Debe habilitar manualmente la funcionalidad de SnapMirror en el nivel del clúster a través de la interfaz de usuario de NetApp Element. El sistema viene con la funcionalidad de SnapMirror deshabilitada de forma predeterminada y no se habilita automáticamente como parte de una nueva instalación o actualización. Habilitar la función SnapMirror es una tarea de configuración que solo debe hacer una vez. 
---
= Habilite SnapMirror en el clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe habilitar manualmente la funcionalidad de SnapMirror en el nivel del clúster a través de la interfaz de usuario de NetApp Element. El sistema viene con la funcionalidad de SnapMirror deshabilitada de forma predeterminada y no se habilita automáticamente como parte de una nueva instalación o actualización. Habilitar la función SnapMirror es una tarea de configuración que solo debe hacer una vez.

SnapMirror solo se puede habilitar en clústeres que ejecutan el software Element que se usa junto con volúmenes de un sistema ONTAP de NetApp. Solo debe habilitar la funcionalidad SnapMirror si el clúster está conectado para usarlo con volúmenes de ONTAP de NetApp.

.Lo que necesitará
El clúster de almacenamiento debe ejecutar el software NetApp Element.

.Pasos
. Haga clic en *Clusters* > *Configuración*.
. Busque la configuración específica del clúster para SnapMirror.
. Haga clic en *Activar SnapMirror*.
+

NOTE: Al habilitar la funcionalidad SnapMirror, se modifica la configuración del software Element de forma permanente. Puede deshabilitar la función SnapMirror y restaurar la configuración predeterminada solo si devuelve el clúster a la imagen de fábrica.

. Haga clic en *Sí* para confirmar el cambio de configuración de SnapMirror.

