---
permalink: storage/task_system_manage_virtual_edit_a_virtual_network.html 
sidebar: sidebar 
keywords: virtual network, edit, ip address block, vlan attributes 
summary: Es posible cambiar los atributos de VLAN, como el nombre de la VLAN, la máscara de red y el tamaño de los bloques de dirección IP. La etiqueta de VLAN y la SVIP no se pueden modificar para una VLAN. El atributo de la puerta de enlace no es un parámetro válido para una VLAN sin VRF. 
---
= Editar una red virtual
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_determine_which_VLAN_IP%27s_are_in_use_and_which_nodes_those_IP%27s_are_assigned_to_in_Element
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar los atributos de VLAN, como el nombre de la VLAN, la máscara de red y el tamaño de los bloques de dirección IP. La etiqueta de VLAN y la SVIP no se pueden modificar para una VLAN. El atributo de la puerta de enlace no es un parámetro válido para una VLAN sin VRF.

Si existe alguna sesión de iSCSI, replicación remota u otras sesiones de red, se podría producir un error en la modificación.

Al administrar el tamaño de los rangos de direcciones IP de VLAN, debe tener en cuenta las siguientes limitaciones:

* Solo es posible eliminar direcciones IP del rango de direcciones IP iniciales asignado en el momento en que se creó la VLAN.
* Puede eliminar un bloque de direcciones IP que se agregó después del rango de direcciones IP inicial, pero no puede cambiar el tamaño de un bloque IP eliminando las direcciones IP.
* Cuando intenta quitar direcciones IP, ya sea del rango de direcciones IP inicial o de un bloque IP, que están utilizando los nodos en el clúster, la operación puede generar un error.
* No se pueden reasignar direcciones IP específicas en uso a otros nodos del clúster.


Puede agregar un bloque de direcciones IP mediante el siguiente procedimiento:

. Seleccione *Cluster* > *Red*.
. Seleccione el icono Actions de la VLAN que quiera editar.
. Seleccione *Editar*.
. En el cuadro de diálogo *Editar VLAN*, introduzca los nuevos atributos para la VLAN.
. Seleccione *Agregar un bloque* para agregar un bloque no continuo de direcciones IP para la red virtual.
. Seleccione *Guardar cambios*.


.Enlace a artículos de la base de conocimientos de solución de problemas
Enlace a los artículos de la base de conocimientos para obtener ayuda sobre la solución de problemas relacionados con la gestión de los intervalos de direcciones IP de VLAN.

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Duplicate_IP_warning_after_adding_a_storage_node_in_VLAN_on_Element_cluster["Duplique la advertencia de IP después de añadir un nodo de almacenamiento en VLAN en el clúster de Element"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_determine_which_VLAN_IP%27s_are_in_use_and_which_nodes_those_IP%27s_are_assigned_to_in_Element["Cómo determinar a qué IP de VLAN están en uso y a qué nodos están asignados esas IP en Element"^]

