---
permalink: storage/task_data_protection_back_up_volume_to_openstack_swift.html 
sidebar: sidebar 
keywords: volume backup, openstack swift object store 
summary: Es posible realizar backups de volúmenes de en almacenes de objetos externos que sean compatibles con OpenStack Swift. 
---
= Realice backups de un volumen en un almacén de objetos OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible realizar backups de volúmenes de en almacenes de objetos externos que sean compatibles con OpenStack Swift.

. Haga clic en *Administración* > *volúmenes*.
. Haga clic en el icono Actions del volumen del que desea realizar un backup.
. En el menú que se abre, haga clic en *copia de seguridad en*.
. En el cuadro de diálogo *copia de seguridad integrada* en *copia de seguridad a*, seleccione *Swift*.
. Seleccione un formato de datos en *Formato de datos*:
+
** *Original*: Formato comprimido que sólo pueden leer los sistemas de almacenamiento SolidFire.
** *Sin comprimir*: Formato sin comprimir compatible con otros sistemas.


. Introduzca una dirección URL para acceder al almacén de objetos en el campo *URL*.
. Introduzca un nombre de usuario para la cuenta en el campo *Nombre de usuario*.
. Introduzca la clave de autenticación de la cuenta en el campo *clave de autenticación*.
. Introduzca el contenedor en el que desea almacenar la copia de seguridad en el campo *Container*.
. *Opcional*: Introduzca una etiqueta de nombre para adjuntarla al prefijo en el campo *nametag*.
. Haga clic en *Iniciar lectura*.

