---
permalink: esds/reference_esds_containerlogs.html 
sidebar: sidebar 
keywords: element, solidfire esds, get container logs, sds containers 
summary: Obtenga más información acerca de los contenedores SolidFire eSDS y dónde obtener los registros asociados con ellos. La información que se proporciona aquí es para ayudarle a comenzar a recopilar registros para la solución de problemas. La mejor forma de solicitar el soporte de NetApp es que los ingenieros formados, que estén bien versados sobre el análisis de los registros, puedan resolver los problemas. 
---
= Recopile registros del contenedor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Obtenga más información acerca de los contenedores SolidFire eSDS y dónde obtener los registros asociados con ellos. La información que se proporciona aquí es para ayudarle a comenzar a recopilar registros para la solución de problemas. Es mejor participar https://www.netapp.com/company/contact-us/support/["Soporte de NetApp"^], donde los ingenieros entrenados conocen bien el análisis de registros pueden ayudar a resolver los problemas.

SolidFire eSDS incluye los siguientes contenedores:

* Contenedor de elementos (`element`): Aloja todos los servicios de elementos en un único contenedor.
* Contenedor de autenticación de elementos (`element_auth`): Proporciona autenticación multifactor (MFA) y tokens de autenticación de sesión para las interfaces de usuario de administración.
* Contenedor de vigilancia de red (`sfnetwd`): Proporciona supervisión beat de la instancia de elemento local y conmutación por error de las IP virtuales (MVIP y SVIP).


Para acceder a los contenedores de un nodo eSDS a través de SSH, el propietario del nodo debe habilitar SSH y proporcionar las credenciales de inicio de sesión. Una vez que tenga acceso SSH al sistema host, puede comprobar el estado de uno o más contenedores mediante el `podman ps` comando. Vea el ejemplo siguiente:

[listing]
----
# podman ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f6b8817c024a localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 10 seconds ago sfnetwd
c3fed6141259 localhost/solidfire-auth:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 11 seconds ago element_auth
1ffa8289c701 localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 12 seconds ago Up 12 seconds ago element
#
----

IMPORTANT: Si uno de los contenedores no está en funcionamiento o en funcionamiento, no utilice Podman para controlar directamente (detener o iniciar) los contenedores. El software Element se controla mediante la `solidfire systemd` unidad de servicio. Este servicio utiliza `elementctl` Para orquestar el software que se ejecuta en los tres contenedores de elementos. Uso `systemctl` Para controlar el servicio SolidFire en el host se recomienda y es compatible la forma de iniciar y detener el software Element en cualquier nodo; sin embargo, hacerlo en un clúster activo solo se debe realizar bajo la supervisión del equipo de soporte de.

Todos los registros relacionados con SolidFire eSDS se pueden encontrar en `/var/log/solidfire/` en el host, el cual se mantiene durante instancias de contenedores. Este directorio contiene los registros del contenedor de Element y contiene el `element_auth/` y.. `sfnetwd/` subdirectorios, que contienen los registros de `element_auth` y.. `sfnetwd` contenedores, respectivamente. Desde dentro de un contenedor, puede acceder a los registros específicos del contenedor en `/var/log`.



== Utilice la interfaz de usuario de Cloud Control de NetApp para recopilar registros

Es posible recoger registros para enviar al soporte de NetApp y ayudarle a diagnosticar problemas con los clústeres eSDS de SolidFire.

Tenga en cuenta las siguientes consideraciones para recoger registros:

* No utilice los comandos de Podman para recopilar registros.
* El soporte de NetApp utiliza una recogida para la recogida de registros de host. Para obtener una experiencia de soporte óptima, debe haber instalado un recopilar.


.Pasos
. Abra la dirección IP del nodo de gestión en un navegador web. Por ejemplo:
+
[listing]
----
https://[management node IP address]
----
. Inicie sesión en Hybrid Cloud Control de NetApp proporcionando las credenciales de administrador del clúster de almacenamiento.
. En el panel de control, seleccione el menú de la parte superior derecha.
. Seleccione *recopilar registros*.
. Seleccione un intervalo de fechas en el menú desplegable *intervalo de fechas* para especificar las fechas que deben incluir los registros.
+
Si especifica una fecha de inicio personalizada, puede seleccionar la fecha para comenzar el rango de fechas. Los registros se recogerán a partir de esa fecha hasta la hora actual.

. En la sección *Log Collection*, seleccione el clúster de almacenamiento o nodos de almacenamiento específicos.
. Seleccione *recopilar registros* para iniciar la recopilación de registros.
+
La recogida de registros se ejecuta en segundo plano y la página muestra el progreso.

+

NOTE: Dependiendo de los registros que recoja, la barra de progreso puede permanecer en un porcentaje determinado durante varios minutos o avanzar muy lentamente en algunos puntos.

. Seleccione *Descargar registros* para descargar el paquete de registro.
+
El paquete de registro está en un UNIX comprimido `.tgz` formato de archivo.





== Obtenga más información

* https://www.netapp.com/data-storage/solidfire/documentation/["Página de recursos de SolidFire de NetApp"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

