---
permalink: esds/task_esds_uninstall.html 
sidebar: sidebar 
keywords: solidfire esds, uninstalling solidfire esds, ansible role 
summary: Puede “restablecer” un nodo en el que instaló SolidFire eSDS quitando SolidFire eSDS en el nodo. Para restablecer SolidFire eSDS en el nodo, debe realizar todos los pasos de instalación. 
---
= Desinstale SolidFire eSDS en el nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede *restablecer* un nodo en el que instaló SolidFire eSDS quitando SolidFire eSDS en el nodo. Para restablecer SolidFire eSDS en el nodo, debe realizar todos los pasos de instalación.


NOTE: Puede utilizar el enlace:https://github.com/NetApp-Automation/nar_solidfire_sds_uninstall[`nar_solidfire_sds_uninstall`#] rol de Ansible proporcionado por NetApp para llevar a cabo la operación. Si desea quitar manualmente SolidFire eSDS en el nodo, consulte los pasos a continuación.

.Pasos
. Quite las unidades del clúster mediante la interfaz de usuario de Element o el[`RemoveDrives`Método API.
+
Esto provoca que el sistema migre los datos desde las unidades del nodo a otras unidades en el clúster. El tiempo que se tarda en realizar este proceso depende de la cantidad de datos que haya que migrar.

. Quite el nodo del clúster mediante la interfaz de usuario de Element o el[`RemoveNodes`Método API.
. Utilice SSH para conectarse al nodo que se ha quitado del clúster.
. Quite SolidFire eSDS del nodo de la siguiente manera:
+
[listing]
----
yum remove solidfire-element
----
. Elimine los datos persistentes del directorio del siguiente modo:
+
[listing]
----
rm -rf /opt/sf
----




== Obtenga más información

* https://www.netapp.com/data-storage/solidfire/documentation/["Página de recursos de SolidFire de NetApp"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

