---
permalink: api/concept_element_api_vvols_api_methods.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,API,method 
summary: 'Los métodos de API de volumen virtual del software Element permiten gestionar los volúmenes virtuales \(VVols\). Los VVol existentes se pueden ver con estos métodos API, así como crear, modificar y eliminar contenedores de almacenamiento de volúmenes virtuales. Aunque no puede utilizar estos métodos para funcionar en volúmenes normales, puede utilizar los métodos de API de volumen normales para enumerar la información sobre VVol.' 
---
= Métodos de API para volúmenes virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los métodos de API de volumen virtual del software Element permiten gestionar volúmenes virtuales (VVol). Los VVol existentes se pueden ver con estos métodos API, así como crear, modificar y eliminar contenedores de almacenamiento de volúmenes virtuales. Aunque no puede utilizar estos métodos para funcionar en volúmenes normales, puede utilizar los métodos de API de volumen normales para enumerar la información sobre VVol.

* xref:reference_element_api_createstoragecontainer.adoc[CreateStorageContainer]
* xref:reference_element_api_deletestoragecontainers.adoc[DeleteStorageContainers]
* xref:reference_element_api_getstoragecontainerefficiency.adoc[GetStorageContainerEfficiency]
* xref:reference_element_api_getvirtualvolumecount.adoc[GetVirtualVolumeCount]
* xref:reference_element_api_listprotocolendpoints.adoc[ListProtocolEndpoints]
* xref:reference_element_api_liststoragecontainers.adoc[ListStorageContainers]
* xref:reference_element_api_listvirtualvolumebindings.adoc[ListVirtualVolumeBindings]
* xref:reference_element_api_listvirtualvolumehosts.adoc[ListVirtualVolumeHosts]
* xref:reference_element_api_listvirtualvolumes.adoc[ListVirtualVolumes]
* xref:reference_element_api_listvirtualvolumetasks.adoc[ListVirtualVolumeTasks]
* xref:reference_element_api_modifystoragecontainer.adoc[ModificyStorageContainer]




== Obtenga más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

