---
permalink: api/concept_element_api_drive_api_methods.html 
sidebar: sidebar 
keywords: drive,API,methods,method 
summary: Es posible usar los métodos de API de unidad para añadir y gestionar unidades que están disponibles para un clúster de almacenamiento. Cuando se añade un nodo de almacenamiento al clúster de almacenamiento o se instalan unidades nuevas en un nodo de almacenamiento existente, las unidades se pueden añadir al clúster de almacenamiento. 
---
= Métodos de API de unidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar los métodos de API de unidad para añadir y gestionar unidades que están disponibles para un clúster de almacenamiento. Cuando se añade un nodo de almacenamiento al clúster de almacenamiento o se instalan unidades nuevas en un nodo de almacenamiento existente, las unidades se pueden añadir al clúster de almacenamiento.

* xref:reference_element_api_adddrives.adoc[AddDrives]
* xref:reference_element_api_getdrivehardwareinfo.adoc[GetDriveHardwarwareInfo]
* xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
* xref:reference_element_api_listdrives.adoc[ListDrives]
* xref:reference_element_api_listdrivestats.adoc[ListDriveStats]
* xref:reference_element_api_removedrives.adoc[RemoveDrives]
* xref:reference_element_api_secureerasedrives.adoc[SecureEraseDrives]




== Obtenga más información

* https://www.netapp.com/data-storage/solidfire/documentation/["Página de recursos de SolidFire de NetApp"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

