---
permalink: api/concept_element_api_about_the_api.html 
sidebar: sidebar 
keywords: SolidFire,API,overview,about,Element 
summary: La API de Element se basa en el protocolo JSON-RPC a través de HTTPS. JSON-RPC es un protocolo RPC sencillo basado en texto que se basa en el formato ligero de intercambio de datos JSON. Las bibliotecas de clientes están disponibles para todos los principales lenguajes de programación. 
---
= Aprenda a administrar el almacenamiento con la API de Element.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La API de Element se basa en el protocolo JSON-RPC a través de HTTPS. JSON-RPC es un protocolo RPC sencillo basado en texto que se basa en el formato ligero de intercambio de datos JSON. Las bibliotecas de clientes están disponibles para todos los principales lenguajes de programación.

Puede realizar solicitudes de API a través de solicitudes HTTPS POSTERIORES al extremo de la API. El cuerpo de la solicitud POST es un objeto de solicitud JSON-RPC. Actualmente, la API no admite solicitudes por lotes (varios objetos de solicitud en UNA SOLA ENTRADA). Cuando envíe solicitudes de API, debe usar "Application/json-rpc" como el tipo de contenido de la solicitud y asegurarse de que el cuerpo no esté codificado en forma.


NOTE: La interfaz de usuario web de Element utiliza los métodos de API que se describen en este documento. Puede supervisar las operaciones de API en la interfaz de usuario habilitando el registro de API; esto permite ver los métodos que se emiten al sistema. Puede activar tanto las solicitudes como las respuestas para ver cómo responde el sistema a los métodos que se emiten.

A menos que se especifique lo contrario, todas las cadenas de fecha de las respuestas API tienen el formato UTC+0.


NOTE: Cuando el clúster de almacenamiento tiene una gran carga o envía muchas solicitudes de API consecutivas sin retrasos, puede que un método falle y devuelva el error "xDBVersionmismatch". Si esto ocurre, vuelva a intentar la llamada al método.



== Objetos comunes

La API del software Element utiliza objetos JSON para representar conceptos de datos organizados. Muchos de estos métodos de API utilizan estos objetos para la entrada y salida de datos. Esta sección documenta estos objetos de uso común; los objetos que sólo se utilizan dentro de un único método se documentan con ese método en lugar de hacerlo en esta sección.

link:../api/reference_element_api_account.html["Aprende sobre objetos comunes"]



== Métodos comunes

Los métodos comunes son los que se utilizan para recuperar información sobre el clúster de almacenamiento, la propia API o las operaciones de API continuas.

link:../api/reference_element_api_getapi.html["Aprenda sobre los métodos comunes"]



== Métodos de API de cuenta

Los métodos de cuentas permiten agregar, quitar, ver y modificar la información de cuenta y seguridad.

link:../api/reference_element_api_addaccount.html["Obtenga información sobre los métodos de la API de cuentas"]



== Métodos API de administrador

Es posible usar métodos de API de administrador para crear, modificar, ver y quitar administradores de clústeres de almacenamiento, así como para asignar niveles de acceso y privilegios a los que tienen acceso a un clúster de almacenamiento.

link:../api/reference_element_api_addclusteradmin.html["Obtenga información sobre los métodos de la API de administrador."]



== Métodos de API de clúster

Los métodos de API de clústeres del software Element permiten gestionar la configuración y la topología del clúster de almacenamiento y los nodos que pertenecen a un clúster de almacenamiento.

Algunos métodos de API de clúster funcionan en nodos que forman parte de un clúster o que se han configurado para unirse a un clúster. Puede añadir nodos a un clúster nuevo o a un clúster existente. Los nodos que están listos para añadirse a un clúster están en estado "pendiente", lo que significa que se han configurado pero que todavía no se han añadido al clúster.

link:../api/reference_element_api_addnodes.html["Aprenda sobre los métodos de la API de clúster"]



== Métodos de la API de creación de clústeres

Puede usar estos métodos API para crear un clúster de almacenamiento de. Todos estos métodos se deben usar contra el extremo de API en un solo nodo.

link:../api/reference_element_api_checkproposedcluster.html["Aprenda sobre los métodos de la API de creación de clústeres."]



== Métodos de API de unidad

Es posible usar los métodos de API de unidad para añadir y gestionar unidades que están disponibles para un clúster de almacenamiento. Cuando se añade un nodo de almacenamiento al clúster de almacenamiento o se instalan unidades nuevas en un nodo de almacenamiento existente, las unidades se pueden añadir al clúster de almacenamiento.

link:../api/reference_element_api_adddrives.html["Aprenda sobre los métodos de la API de Drive"]



== Métodos de API de Fibre Channel

Es posible usar métodos de API Fibre Channel para añadir, modificar o quitar miembros de nodos Fibre Channel de un clúster de almacenamiento.

link:../api/reference_element_api_getvolumeaccessgrouplunassignments.html["Aprenda sobre los métodos de la API de Fibre Channel"]



== Métodos de API del iniciador

Los métodos de iniciador permiten añadir, quitar, ver y modificar objetos de iniciador iSCSI, que controlan la comunicación entre el sistema de almacenamiento y los clientes de almacenamiento externos.

link:../api/reference_element_api_createinitiators.html["Aprenda sobre los métodos de la API de iniciación"]



== Métodos de API de LDAP

Puede usar el protocolo ligero de acceso a directorios (LDAP) para autenticar el acceso al almacenamiento de Element. Los métodos de API de LDAP que se describen en esta sección le permiten configurar el acceso LDAP al clúster de almacenamiento.

link:../api/reference_element_api_addldapclusteradmin.html["Aprenda sobre los métodos de la API de LDAP"]



== Métodos de API de autenticación multifactor

Puede usar la autenticación multifactor (MFA) para gestionar las sesiones de usuario usando un proveedor de identidades (IDP) de terceros a través del lenguaje de marcado de aserción de seguridad (SAML).

link:../api/reference_element_api_addidpclusteradmin.html["Aprenda sobre los métodos de la API de autenticación multifactor."]



== Métodos API de autenticación de sesión

Es posible usar la autenticación basada en sesiones para gestionar sesiones de usuario.

link:../api/reference_element_api_listauthsessionbyclusteradmin.html["Aprenda sobre los métodos de la API de autenticación de sesión"]



== Métodos de API de nodo

Puede usar métodos API de nodo para configurar nodos individuales. Estos métodos funcionan en nodos únicos que se deben configurar, se han configurado pero que aún no participan en un clúster o que participan activamente en un clúster. Los métodos de API de nodos le permiten ver y modificar la configuración de los nodos individuales y la red de clústeres que se usa para comunicarse con el nodo. Debe ejecutar estos métodos en nodos individuales; no puede ejecutar métodos de API por nodo en comparación con la dirección del clúster.

link:../api/reference_element_api_checkpingonvlan.html["Aprende sobre los métodos de la API de Node."]



== Métodos de API de replicación

Los métodos de API de replicación permiten conectar dos clústeres para la protección continua de datos (CDP). Cuando se conectan dos clústeres, los volúmenes activos en un clúster se pueden replicar de manera continua en un segundo clúster para proporcionar recuperación de datos. Al emparejar volúmenes para la replicación, es posible proteger los datos de eventos que podrían no ser accesibles.

link:../api/reference_element_api_cluster_pairing_order_of_operations.html["Aprenda sobre los métodos de la API de replicación"]



== Métodos de API de seguridad

Es posible integrar el software Element con servicios relacionados con la seguridad externos, como un servidor de gestión de claves externo. Estos métodos relacionados con la seguridad permiten configurar funciones de seguridad de Element, como la gestión de claves externa para el cifrado en reposo.

link:../api/reference_element_api_addkeyservertoproviderkmip.html["Aprenda sobre los métodos de la API de seguridad"]



== Métodos de API de SnapMirror

La interfaz de usuario web de Element utiliza los métodos de API de SnapMirror para gestionar copias de Snapshot reflejadas con sistemas ONTAP remotos. Estos métodos están destinados únicamente a su uso en la interfaz de usuario web de Element. Si necesita acceso mediante API a la funcionalidad SnapMirror, utilice las API de ONTAP. No se proporcionan ejemplos de solicitud y devolución para los métodos de API de SnapMirror.

link:../api/reference_element_api_abortsnapmirrorrelationship.html["Aprenda sobre los métodos de la API de SnapMirror"]



== Métodos de la API de configuración del sistema

Los métodos de API de configuración del sistema le permiten obtener y establecer valores de configuración que se aplican a todos los nodos del clúster.

link:../api/reference_element_api_disablebmccoldreset.html["Aprenda sobre los métodos de la API de configuración del sistema."]



== Métodos de API de redes múltiples inquilinos

Las redes multitenant en clústeres de almacenamiento de Element permiten que el tráfico entre varios clientes en redes lógicas independientes se conecten a un clúster de almacenamiento de Element sin enrutamiento de la capa 3.

Las conexiones al clúster de almacenamiento se separan en la pila de redes mediante el etiquetado de VLAN.



=== Requisitos previos para configurar una red virtual multitenant

* Se debe haber identificado el bloque de direcciones IP de red de cliente que se asignarán a las redes virtuales en los nodos de almacenamiento.
* Se debe haber identificado la dirección IP de red de almacenamiento de cliente (SVIP) que se usará como extremo para todo el tráfico de almacenamiento de.




=== Orden de operaciones de red virtual

. Utilice el método AddVirtualNetwork para aprovisionar en lote las direcciones IP que introduzca.
+
Después de añadir una red virtual, el clúster realiza de forma automática los siguientes pasos:

+
** Cada nodo de almacenamiento crea una interfaz de red virtual.
** A cada nodo de almacenamiento se le asigna una dirección VLAN que se puede enrutar con la SVIP virtual.
** Las direcciones IP de VLAN persisten en cada nodo en el caso de que se reinicie un nodo.


. Cuando se asignan la interfaz de red virtual y las direcciones VLAN, es posible asignar el tráfico de red de cliente a la SVIP virtual.


link:../api/concept_element_api_virtual_network_naming_conventions.html["Aprenda sobre los métodos de la API de redes multiinquilino"]



== Métodos de API de volumen

Los métodos de la API de volúmenes del software Element permiten gestionar volúmenes que residen en un nodo de almacenamiento. Puede crear, modificar, clonar y eliminar volúmenes con estos métodos. También puede usar métodos de API de volúmenes para recopilar y mostrar mediciones de datos de un volumen.

link:../api/reference_element_api_cancelclone.html["Aprenda sobre los métodos de la API de volumen"]



== Métodos API de grupo de acceso de volúmenes

Los métodos de grupo de acceso de volúmenes permiten añadir, quitar, ver y modificar grupos de acceso de volúmenes, que son colecciones de volúmenes a los que los usuarios pueden acceder mediante iniciadores iSCSI o Fibre Channel.

link:../api/reference_element_api_addinitiatorstovolumeaccessgroup.html["Obtenga información sobre los métodos de la API de grupos de acceso por volumen."]



== Métodos de API de Snapshot de volumen

Los métodos de la API de Snapshot de volumen del software Element permiten gestionar copias de Snapshot de volumen. Es posible crear, modificar, clonar y eliminar copias de Snapshot de volumen con los métodos de API de snapshot de volumen.

link:../api/concept_element_api_snapshots_overview.html["Aprenda sobre los métodos de la API de instantáneas de volumen"]



== Métodos de API para volúmenes virtuales

Los métodos de API de volumen virtual del software Element permiten gestionar volúmenes virtuales (VVol). Los VVol existentes se pueden ver con estos métodos API, así como crear, modificar y eliminar contenedores de almacenamiento de volúmenes virtuales. Aunque no puede utilizar estos métodos para funcionar en volúmenes normales, puede utilizar los métodos de API de volumen normales para enumerar la información sobre VVol.

link:../api/reference_element_api_createstoragecontainer.html["Aprenda sobre los métodos de la API de volumen virtual"]



== Obtenga más información

* https://docs.netapp.com/us-en/element-software/index.html["Documentación de SolidFire y el software Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentación para versiones anteriores de SolidFire de NetApp y los productos Element"^]

