---
permalink: api/reference_element_api_modifyinitiators.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,initiators,initiator,attribute,attributes,modifyinitiators 
summary: Puede usar el método ModifyInitiators para cambiar los atributos de uno o más iniciadores existentes. 
---
= ModificyInitiators
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ModifyInitiators` método para cambiar los atributos de uno o más iniciadores existentes.

No puede cambiar el nombre de un iniciador existente. Si necesita cambiar el nombre de un iniciador, elimínelo primero con el xref:reference_element_api_deleteinitiators.adoc[DeleteInitiators] y cree uno nuevo con el xref:reference_element_api_createinitiators.adoc[CreateInitiators] método.

Si ModifyInitiators no cambia uno de los iniciadores proporcionados en el parámetro, el método devuelve un error y no modifica ningún iniciador (no es posible completar parcialmente).



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===


| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
iniciadores
 a| 
Una lista de objetos que contienen características de cada iniciador que se va a modificar. Objetos posibles:

* `alias`: (Opcional) un nuevo nombre descriptivo que se debe asignar al iniciador. (cadena)
* `attributes`: (Opcional) un nuevo conjunto de atributos JSON que se asignarán al iniciador. (Objeto JSON)
* `chapUsername`: (Opcional) un nuevo nombre de usuario CHAP único para este iniciador. (cadena)
* `forceDuringUpgrade`: Complete la modificación del iniciador durante una actualización.
* `initiatorID`: (Obligatorio) el ID del iniciador que se va a modificar. (entero)
* `initiatorSecret`: (Opcional) un nuevo secreto CHAP utilizado para autenticar al iniciador. (cadena)
* `requireChap`: (Opcional) True si se requiere CHAP para este iniciador. (booleano)
* `targetSecret`: (Opcional) un nuevo secreto CHAP utilizado para autenticar el destino (al utilizar la autenticación CHAP mutua). (cadena)
* `virtualNetworkIDs`: (Opcional) la lista de identificadores de red virtual asociados con este iniciador. Si define una o más redes virtuales, este iniciador solo puede iniciar sesión en esas redes virtuales. Si no define ninguna red virtual, este iniciador puede iniciar sesión en todas las redes.
* `volumeAccessGroupID`: (Opcional) el ID del grupo de acceso de volúmenes al que se debe añadir el iniciador. Si el iniciador se encontraba previamente en un grupo de acceso de volúmenes diferente, se elimina del grupo de acceso de volúmenes antiguo. Si esta clave está presente pero es nula, el iniciador se elimina de su grupo de acceso de volúmenes actual, pero no se coloca en ningún grupo de acceso de volúmenes nuevo. (entero)

 a| 
Cabina de objetos JSON
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
iniciadores
 a| 
Lista de objetos que describen los iniciadores recién modificados.
 a| 
xref:reference_element_api_initiator.adoc[iniciador] cabina

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "id": 6683,
  "method": "ModifyInitiators",
  "params": {
    "initiators": [
      {
        "initiatorID": 2,
        "alias": "alias1",
        "volumeAccessGroupID": null
      },
      {
        "initiatorID": 3,
        "alias": "alias2",
        "volumeAccessGroupID": 1
      }
    ]
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 6683,
  "result": {
    "initiators": [
      {
        "alias": "alias1",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:395543635",
        "volumeAccessGroups": []
      },
      {
        "alias": "alias2",
        "attributes": {},
        "initiatorID": 3,
        "initiatorName": "iqn.1993-08.org.debian:01:935573135",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Nuevo desde la versión

9.6



== Obtenga más información

* xref:reference_element_api_createinitiators.adoc[CreateInitiators]
* xref:reference_element_api_deleteinitiators.adoc[DeleteInitiators]

