---
permalink: api/reference_element_api_createsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,create,creating,snapshot,snapshots,CreateSnapshot 
summary: Es posible utilizar CreateSnapshot para crear una copia de un momento específico de un volumen. Es posible crear una snapshot desde cualquier volumen o desde una snapshot existente. 
---
= CreateSnapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar `CreateSnapshot` para crear una copia de un momento específico de un volumen. Es posible crear una snapshot desde cualquier volumen o desde una snapshot existente.

Si no se proporciona un identificador de copia Snapshot con este método de API, se crea una copia Snapshot a partir de la rama activa del volumen. Si el volumen a partir del que se crea la snapshot se está replicando en un clúster remoto, la snapshot también puede replicarse en el mismo destino. Use el parámetro enableRemoteReplication para habilitar la replicación Snapshot.


NOTE: Puede crear copias de Snapshot si la ocupación del clúster se encuentra en la etapa 1, 2 o 3. No se pueden crear copias de Snapshot cuando la ocupación del clúster llegue a la etapa 4 o 5.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
`attributes`
 a| 
La lista de pares nombre-valor en el formato de objetos JSON.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
`enableRemoteReplication`
 a| 
Especifica si la copia de Snapshot se replicará o no en el almacenamiento remoto. Los posibles valores son los siguientes:

* `true`: La instantánea se replicará en el almacenamiento remoto.
* `false`: La instantánea no se replicará en el almacenamiento remoto.

 a| 
booleano
 a| 
falso
 a| 
No



| `ensureSerialCreation`  a| 
Especifica que no se debe crear la instantánea si hay una replicación de instantánea anterior en curso. Los valores posibles son:

* `true`: Esto garantiza que sólo se replica una instantánea a la vez. Se producirá un error al crear una nueva snapshot si aún hay una replicación de snapshot anterior en curso.
* `false`: Predeterminado. Esta creación de snapshot se permite si otra replicación de snapshot aún está en curso.

| booleano | `false` | No 


| Tiempo de caducidad  a| 
Especifique la hora después de la cual puede eliminarse la snapshot. No se puede utilizar con `retention`. Si no se especifica ni el tiempo de caducidad ni la retención, la snapshot no caducará. El formato de hora es una cadena de fecha ISO 8601 para vencimiento basado en tiempo; de lo contrario, no caducará. Valor de `null` hace que la copia de snapshot se retenga de forma permanente. Valor de `fifo` Hace que la instantánea se conserve primero en salir, con relación a otras instantáneas del FIFO del volumen. La API fallará si no hay espacio FIFO disponible.
| cadena | Ninguno | No 


 a| 
`name`
 a| 
El nombre de la copia de Snapshot. Si no se introduce ningún nombre, se utilizará la fecha y la hora en que se realizó la instantánea. La longitud máxima permitida para el nombre es de 255 caracteres.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
`retention`
 a| 
Este parámetro es el mismo que el `expirationTime` El parámetro, excepto el formato de hora es HH:mm:ss Si ninguno `expirationTime` tampoco `retention` se especifican, la instantánea no caducará.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
`snapMirrorLabel`
 a| 
La etiqueta que utiliza el software SnapMirror para especificar la política de retención de snapshots en un extremo de SnapMirror.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
`snapshotID`
 a| 
El ID exclusivo de una copia de Snapshot a partir de la cual se realiza la nueva copia de Snapshot. El ID de copia Snapshot aprobada debe ser una copia de Snapshot en un volumen determinado.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
`volumeID`
 a| 
ID único de la imagen de volumen de la que se desea copiar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===


| Nombre | Descripción | Tipo 


 a| 
suma de comprobación
 a| 
Una cadena que representa los dígitos correctos de la instantánea almacenada. Esta suma de comprobación se puede utilizar más adelante para comparar otras instantáneas con el fin de detectar errores en los datos.
 a| 
cadena



 a| 
ID de copia Snapshot
 a| 
El ID exclusivo de la snapshot nueva.
 a| 
ID de snapshot



 a| 
snapshot
 a| 
Un objeto que contiene información acerca de la snapshot recién creada.
 a| 
xref:reference_element_api_snapshot.adoc[snapshot]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "CreateSnapshot",
   "params": {
      "volumeID": 1
   },
   "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "checksum": "0x0",
      "snapshot": {
        "attributes": {},
        "checksum": "0x0",
        "createTime": "2016-04-04T17:14:03Z",
        "enableRemoteReplication": false,
        "expirationReason": "None",
        "expirationTime": null,
        "groupID": 0,
        "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
        "name": "2016-04-04T17:14:03Z",
        "snapshotID": 3110,
        "snapshotUUID": "6f773939-c239-44ca-9415-1567eae79646",
        "status": "done",
        "totalSize": 5000658944,
        "virtualVolumeID": null,
        "volumeID": 1
      },
        "snapshotID": 3110
  }
}
----


== Excepción

Una excepción xNotPrimary se muestra cuando la `CreateSnapshot` Se llama a la API y la snapshot no se puede crear. Este es el comportamiento esperado. Vuelva a intentar el `CreateSnapshot` Llamada a API.



== Nuevo desde la versión

9.6
