---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: Es posible usar el método ListVolumeStatsByVolumeAccessGroup para enumerar las mediciones de la actividad total de todos los volúmenes que son miembros de los grupos de acceso de volúmenes especificados. 
---
= ListVolumeStatsByVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListVolumeStatsByVolumeAccessGroup` método para enumerar las mediciones de actividad total de todos los volúmenes que son miembros de los grupos de acceso de volúmenes especificados.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
IncludeVirtualVolumes
 a| 
De forma predeterminada, se incluyen los volúmenes virtuales en la respuesta. Para excluir volúmenes virtuales, se debe establecer en FALSE.
 a| 
booleano
 a| 
verdadero
 a| 
No



 a| 
VolumeAccessGroups
 a| 
Una matriz de VolumeAccessGroupID para la que se devuelve la actividad del volumen. Si se omite, se devuelven las estadísticas de todos los grupos de acceso de volúmenes.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
VolumeStats
 a| 
Lista de información de actividad de volumen para todos los volúmenes del grupo de acceso de volumen especificado.*Nota:* el miembro volumeID es 0 para cada entrada, ya que los valores representan la suma de todos los volúmenes propiedad de la cuenta.
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStats]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== Nuevo desde la versión

9.6
