---
permalink: api/reference_element_api_deletevolumes.html 
sidebar: sidebar 
keywords: volumes,volume,delete,deleting,multiple,DeleteVolumes 
summary: 'Puede utilizar el método DeleteVolumes para marcar varios \(hasta 500\) volúmenes activos para su eliminación. Una vez marcado, el volumen se purga \(permanentemente eliminado\) después de que transcurra el intervalo de limpieza.' 
---
= DeleteVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `DeleteVolumes` método para marcar varios (hasta 500) volúmenes activos para su eliminación. Una vez marcado, el volumen se purga (se elimina permanentemente) después de que transcurre un intervalo de limpieza.

Una vez que se realiza una solicitud para eliminar volúmenes, todas las conexiones iSCSI activas con los volúmenes se finalizan inmediatamente y no se permiten más conexiones mientras los volúmenes están en este estado. No se devuelve un volumen marcado en las solicitudes de detección de objetivos.

Las copias de Snapshot de un volumen marcadas para eliminación no se ven afectadas. Las Snapshot se conservan hasta que se purga el volumen del sistema. Si se Marca un volumen para eliminación y tiene una operación de lectura masiva de volúmenes o escritura masiva en curso, se detiene la operación de lectura o escritura masiva de volúmenes.

Si los volúmenes que se eliminan se emparejan con un volumen, la replicación entre los volúmenes emparejados se suspende y no se transfieren datos a ellos o de ellos mientras se encuentran en estado eliminado. Los volúmenes remotos cuyos volúmenes eliminados se emparejaron con entran en estado PausedMisconfigured y ya no se envían los datos a ellos o desde los volúmenes eliminados. Hasta que se purguen los volúmenes eliminados, se pueden restaurar y se pueden reanudar las transferencias de datos. Si los volúmenes eliminados se purgan del sistema, los volúmenes se emparejaron con se introducen en el estado StoppedMisconfigured y se elimina el estado del emparejamiento de volúmenes. Los volúmenes purgados dejan de estar disponibles de forma permanente.



== Parámetros

Este método tiene los siguientes parámetros de entrada.


NOTE: Se requiere al menos uno de los siguientes parámetros, y debe usar solo uno de ellos (todos se excluyen uno al otro).

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
ID de volumen
 a| 
La lista de ID de los volúmenes que se van a eliminar del sistema.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
Consulte Nota.



 a| 
VolumeAccessGroupID
 a| 
Una lista de los ID de grupo de acceso de volúmenes. Todos los volúmenes de todos los grupos de acceso de volúmenes especificados en esta lista se eliminan del sistema.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
Consulte Nota.



 a| 
ID de cuenta
 a| 
Lista de ID de cuenta. Todos los volúmenes de estas cuentas se eliminan del sistema.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
Consulte Nota.

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===


| Nombre | Descripción | Tipo 


 a| 
volúmenes
 a| 
Información acerca del volumen recién eliminado.
 a| 
xref:reference_element_api_volume.adoc[volumen]



 a| 
curva
 a| 
La curva es un conjunto de pares clave-valor. Las claves son los tamaños de I/o en bytes. Los valores representan el coste de ejecutar un IOP en un tamaño de I/o específico. La curva se calcula en relación con una operación de 4096 bytes establecida en 100 IOPS.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "DeleteVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----

{
  "id" : 1,
  "result": {
    "volumes" : [ {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {},
      "blockSize": 4096,
      "createTime": "2015-03-06T18:50:56Z",
      "deleteTime": "",
      "enable512e": False,
      "iqn": "iqn.2010-01.com.solidfire:pzsr.vclient-030-v00001.1",
      "name": "vclient-030-v00001",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {},
        "maxIOPS": 15000,
        "minIOPS": 100
      },
      "purgeTime": "",
      "sliceCount": 1,
      "scsiEUIDeviceID": "707a737200000001f47acc0100000000",
      "scsiNAADeviceID": "6f47acc100000000707a737200000001",
      "status": "active",
      "totalSize": 10000003072,
      "virtualVolumeID": 5,
      "volumeAccessGroups": [],
      "volumePairs": [],
      "volumeID": 1
    } ]
  }
}
----


== Nuevo desde la versión

9.6
