---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: Puede utilizar el método ListAuthSessionsByUsername para mostrar todas las sesiones de autenticación del usuario especificado. Un llamante que no esté en los privilegios de administrador/administradores de clúster de AccessGroup sólo puede enumerar sus propias sesiones. Una persona que llama con privilegios de administrador/administradores de clúster puede mostrar las sesiones que pertenecen a cualquier usuario. 
---
= ListAuthSessionsByUsername
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListAuthSessionsByUsername` método para mostrar todas las sesiones de autenticación del usuario especificado. Un llamante que no esté en los privilegios de administrador/administradores de clúster de AccessGroup sólo puede enumerar sus propias sesiones. Una persona que llama con privilegios de administrador/administradores de clúster puede mostrar las sesiones que pertenecen a cualquier usuario.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
AuthMethod
 a| 
Método de autenticación de las sesiones de usuario que se mostrarán en la lista. Sólo un llamante del ClusterAdmins/Administrator AccessGroup puede proporcionar este parámetro. Los valores posibles son:

* *AuthMethod=Cluster* especifica el nombre de usuario ClusterAdmin.
* *AuthMethod=LDAP* especifica el DN LDAP del usuario.
* *AuthMethod=IDP* especifica el UUID de IDP del usuario o NameID. Si el IDP no está configurado para devolver ninguna de las dos opciones, esto especifica un UUID aleatorio emitido al crear la sesión.

 a| 
AuthMethod
 a| 
Ninguno
 a| 
Sí



 a| 
nombre de usuario
 a| 
Identificador único del usuario.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
sesiones
 a| 
Lista de información de sesión para las sesiones de autenticación.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nuevo desde la versión

12.0
