---
permalink: api/reference_element_api_setloginsessioninfo.html 
sidebar: sidebar 
keywords: authentication,login,session,info,timeout,setloginsessioninfo 
summary: Puede utilizar el método SetLoginSessionInfo para establecer el período de tiempo durante el cual es válida una autenticación de inicio de sesión para una sesión. Una vez transcurrido el período de inicio de sesión sin actividad en el sistema, caduca la autenticación. Se requieren nuevas credenciales de inicio de sesión para permitir un acceso constante al clúster una vez transcurrido el período de inicio de sesión. 
---
= SetLoginSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `SetLoginSessionInfo` método para establecer el período de tiempo que es válido una autenticación de inicio de sesión para una sesión. Una vez transcurrido el período de inicio de sesión sin actividad en el sistema, caduca la autenticación. Se requieren nuevas credenciales de inicio de sesión para permitir un acceso constante al clúster una vez transcurrido el período de inicio de sesión.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
tiempo de espera
 a| 
Período de vencimiento de la autenticación en clúster. Con formato HH:mm:ss Por ejemplo: 01:30:00, 00:90:00, y 00:00:5400 pueden utilizarse todos para igualar un periodo de tiempo de espera de 90 minutos. El valor de tiempo de espera mínimo es 1 minuto. Cuando no se proporciona un valor, o se configura a cero, la sesión de inicio de sesión no tiene valor de tiempo de espera.
 a| 
cadena
 a| 
30 minutos
 a| 
No

|===


== Valor de retorno

Este método no tiene ningún valor devuelto.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "SetLoginSessionInfo",
  "params": {
    "timeout" : "01:30:00"
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nuevo desde la versión

9.6
