---
permalink: api/reference_element_api_resetdrives.html 
sidebar: sidebar 
keywords: drive,drives,remove,removing,data,reset,resetting,resetdrives,erase 
summary: Es posible utilizar el método ResetDrives para inicializar unidades de forma proactiva y quitar todos los datos que residen actualmente en una unidad. La unidad se puede volver a usar en un nodo existente o se puede usar en un nodo actualizado. 
---
= ResetDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ResetDrives` método para inicializar unidades de forma proactiva y quitar todos los datos que residen actualmente en una unidad. La unidad se puede volver a usar en un nodo existente o se puede usar en un nodo actualizado.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
unidades
 a| 
Lista de nombres de dispositivos (no identificadores de unidades) que se van a restablecer.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
fuerza
 a| 
Configure en TRUE para restablecer la unidad.
 a| 
booleano
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
detalles
 a| 
Detalles de las unidades que se están restableciendo.
 a| 
Cabina de objetos JSON

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "ResetDrives",
   "params": {
      "drives" : "slot3",
      "force" : true
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
   "details": {
    "drives": [
    {
      "drive": "slot3",
      "returnCode": 0,
      "stderr": " * Unlocking /dev/slot9 .[ ok ]\ * Setting master password /dev/slot9 .[ ok ]\ * Secure erasing /dev/slot9 (hdparm) [tries=0/1] ...........................[ ok ]",
      "stdout": ""
    }
   ]
  },
  "duration": "00:00:28.501269",
  "result": "Passed"
  }
}
----


== Nuevo desde la versión

9.6
