---
permalink: api/reference_element_api_listsnapmirrorpolicies.html 
sidebar: sidebar 
keywords: snapmirror,policy,policies,list,listing,ontap,listsnapmirrorpolicies 
summary: La interfaz de usuario web del software Element utiliza el método ListSnapMirrorPolicies para enumerar todas las políticas de SnapMirror en un sistema ONTAP remoto. 
---
= ListSnapMirrorPolicies
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario web del software Element utiliza el `ListSnapMirrorPolicies` Método para enumerar todas las políticas de SnapMirror en un sistema de ONTAP remoto.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
SnapMirrorEndpointID
 a| 
Enumere sólo las políticas asociadas al identificador de extremo especificado. Si no se proporciona ningún ID de extremo, el sistema enumera las políticas de todos los extremos de SnapMirror conocidos.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
SnapMirrorPolicies
 a| 
Una lista de políticas de SnapMirror en el sistema de almacenamiento de ONTAP.
 a| 
xref:reference_element_api_snapmirrorpolicy.adoc[SnapMirrorPolicy] cabina

|===


== Nuevo desde la versión

10.1
