---
permalink: api/reference_element_api_enablesnmp.html 
sidebar: sidebar 
keywords: SNMP,enable,enabling,EnableSNMP 
summary: Puede utilizar el método EnableSnmp para habilitar SNMP en nodos de clúster. Cuando habilita SNMP, la acción se aplica a todos los nodos del clúster y los valores que se pasan reemplazan todos los valores establecidos en cualquier llamada anterior a EnableSnmp. 
---
= EnableSnmp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `EnableSnmp` Método para habilitar SNMP en nodos de clúster. Cuando habilita SNMP, la acción se aplica a todos los nodos del clúster, y los valores que se pasan sustituyen a todos los valores establecidos en cualquier llamada anterior a. `EnableSnmp`.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
SnmpV3Enabled
 a| 
Si se establece en true, SNMP v3 se habilita en cada nodo del clúster. Si se establece en false, se habilita SNMP v2.
 a| 
booleano
 a| 
falso
 a| 
No

|===


== Valor de retorno

Este método no tiene ningún valor devuelto.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "EnableSnmp",
  "params": {
      "snmpV3Enabled"  : "true"
  },
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nuevo desde la versión

9.6
