---
permalink: api/reference_element_api_testremoteconnectivity.html 
sidebar: sidebar 
keywords: remote,connectivity,test,testing,testremoteconnectivity 
summary: Puede usar el método TestRemoteConnectivity para hacer ping a cada nodo del clúster remoto y comprobar la conexión de la base de datos del conjunto remoto. Los clústeres deben emparejarse para devolver resultados útiles con este método. Si la conexión de base de datos remota falla, la respuesta del sistema muestra las excepciones. 
---
= TestRemoteConnectivity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar `TestRemoteConnectivity` método para hacer ping en cada nodo del clúster remoto y comprobar la conexión de la base de datos del conjunto remoto. Los clústeres deben emparejarse para devolver resultados útiles con este método. Si la conexión de base de datos remota falla, la respuesta del sistema muestra las excepciones.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
detalles
 a| 
Tiempos de respuesta ping individuales para cada nodo.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "TestRemoteConnectivity",
    "params": {
      "force": "true"
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": null,
  "result": {
    "details": {
      "1": {
        "details": {
          "10.26.86.17": {
            "individualResponseTimes": [
              "00:00:00.006868",
              "00:00:00.005933",
              "00:00:00.006655",
              "00:00:00.006584",
              "00:00:00.006334"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006475",
            "successful": true
          },
          "10.26.86.18": {
            "individualResponseTimes": [
              "00:00:00.006201",
              "00:00:00.006187",
              "00:00:00.005990",
              "00:00:00.006029",
              "00:00:00.005917"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006065",
            "successful": true
          },
          "10.26.86.19": {
            "individualResponseTimes": [
              "00:00:00.005988",
              "00:00:00.006948",
              "00:00:00.005981",
              "00:00:00.005964",
              "00:00:00.005942"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006165",
            "successful": true,
          },
          "10.26.86.20": {
            "individualResponseTimes": [
              "00:00:00.005926",
              "00:00:00.006072",
              "00:00:00.005675",
              "00:00:00.009904",
              "00:00:00.006225"
            ],
            "individualStatus": [
              "true",
              "true",
              "true",
              "true",
              "true"
            ],
            "responseTime": "00:00:00.006760",
            "successful": true
          }
        },
          "successful": true
      }
    },
  "duration": "00:00:00.595982",
  "result": "Passed"
  }
}
----


== Nuevo desde la versión

9.6
