---
permalink: api/reference_element_api_listsnapmirrorvservers.html 
sidebar: sidebar 
keywords: snapmirror,vserver,vservers,list,listing,listsnapmirrorvservers 
summary: La interfaz de usuario web del software Element usa el método ListSnapMirrorVServers para enumerar todos los vServers de SnapMirror disponibles en un sistema ONTAP remoto. 
---
= ListSnapMirrorservidores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario web del software Element utiliza el `ListSnapMirrorVservers` Método para enumerar todos los vServers de SnapMirror disponibles en un sistema ONTAP remoto.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
SnapMirrorEndpointID
 a| 
Enumere sólo los vServers asociados con el identificador de extremo especificado. Si no se proporciona ningún ID de extremo, el sistema enumera los vServers de todos los extremos de SnapMirror conocidos.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
VserverType
 a| 
Enumere solo los vServers del tipo especificado. Los posibles valores son los siguientes:

* admin
* sql server
* nodo
* sistema

 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
Nombre del servidor virtual
 a| 
Enumere solo los vServers con el nombre especificado.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
SnapMirrorVServer
 a| 
Una lista de vServers de SnapMirror disponibles en el sistema de almacenamiento de ONTAP.
 a| 
xref:reference_element_api_snapmirrorvserver.adoc[SnapMirrorVServer] cabina

|===


== Nuevo desde la versión

10.1
