---
permalink: api/reference_element_api_createclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,create,creating,CreateClusterInterfacePreference 
summary: El método CreateClusterInterfacePreference permite a los sistemas integrados con clústeres de almacenamiento que ejecutan el software Element crear y almacenar información arbitraria en el clúster de almacenamiento. Este método es para uso interno. 
---
= CreateClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `CreateClusterInterfacePreference` Método permite a los sistemas integrados con los clústeres de almacenamiento que ejecutan el software Element crear y almacenar información arbitraria en el clúster de almacenamiento. Este método es para uso interno.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
nombre
 a| 
El nombre de la interfaz del clúster preferido.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
valor
 a| 
El valor de la interfaz de clúster preferida.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método no tiene ningún valor devuelto.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
		"method": "CreateClusterInterfacePreference",
		"params": {
			"name": "prefname",
			"value": "testvalue"
		},
	"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result": {}
}
----


== Nuevo desde la versión

11.0
