---
permalink: api/reference_element_api_listvolumeqoshistograms.html 
sidebar: sidebar 
keywords: qos,usage,volume,histogram,generate,listvolumeqoshistograms,histograms 
summary: Puede usar el método ListVolumeQoSHistogramas para generar un histograma del uso de la calidad de servicio de un volumen o de varios volúmenes. Esto le permite comprender mejor cómo los volúmenes están usando la calidad de servicio. 
---
= ListVolumeQoSHistogramas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListVolumeQoSHistograms` Método para generar un histograma del uso de calidad de servicio de un volumen o de varios volúmenes. Esto le permite comprender mejor cómo los volúmenes están usando la calidad de servicio.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
ID de volumen
 a| 
Una lista opcional de ID de volumen que especifica qué volúmenes deben tener generados histogramas de calidad de servicio.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
QosHistogramas
 a| 
Una lista de objetos que describen el uso de volúmenes para uno o más volúmenes.
 a| 
Cabina de objetos JSON

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
	"method": "ListVolumeQoSHistograms",
		"params": {
			"volumeIDs": [1]
		},
	"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result": {
		"qosHistograms": [
		{
			"histograms": {
			"belowMinIopsPercentages": {
				"Bucket1To19": 2406,
				"Bucket20To39": 3,
				"Bucket40To59": 0,
				"Bucket60To79": 4,
				"Bucket80To100": 0
			},
				"minToMaxIopsPercentages": {
				"Bucket101Plus": 0,
				"Bucket1To19": 0,
				"Bucket20To39": 0,
				"Bucket40To59": 2,
				"Bucket60To79": 0,
				"Bucket80To100": 0
			},
				"readBlockSizes": {
				"Bucket131072Plus": 0,
				"Bucket16384To32767": 0,
				"Bucket32768To65535": 0,
				"Bucket4096To8191": 0,
				"Bucket65536To131071": 0,
				"Bucket8192To16383": 0
			},
				"targetUtilizationPercentages": {
				"Bucket0": 134943,
				"Bucket101Plus": 0,
				"Bucket1To19": 2409,
				"Bucket20To39": 4,
				"Bucket40To59": 0,
				"Bucket60To79": 2,
				"Bucket80To100": 0
			},
				"throttlePercentages": {
				"Bucket0": 137358,
				"Bucket1To19": 0,
				"Bucket20To39": 0,
				"Bucket40To59": 0,
				"Bucket60To79": 0,
				"Bucket80To100": 0
			},
				"writeBlockSizes": {
				"Bucket131072Plus": 0,
				"Bucket16384To32767": 0,
				"Bucket32768To65535": 0,
				"Bucket4096To8191": 0,
				"Bucket65536To131071": 0,
				"Bucket8192To16383": 0
			}
		},
			"timestamp": "2018-06-21T18:45:52.010844Z",
			"volumeID": 1
		}
	]
}
}
----