---
permalink: api/reference_element_api_listinitiators.html 
sidebar: sidebar 
keywords: initiators,initiator,list,listing,listinitiators,iqn,wwpn,iqns,wwpns 
summary: 'Puede usar el método ListInitiators para obtener la lista de IQN de iniciador o nombres de puerto WWPN \(WWPN\).' 
---
= ListInitiators
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListInitiators` Método para obtener la lista de IQN de iniciador o nombres de puerto WWPN.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
iniciadores
 a| 
Una lista de ID de iniciador que se desea recuperar. Puede proporcionar este parámetro o el parámetro startInitiatorID, pero no ambos.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
No



 a| 
StartInitiatorID
 a| 
El ID del iniciador en el que comenzar el listado. Puede proporcionar este parámetro o el parámetro Initiators, pero no ambos.
 a| 
entero
 a| 
0
 a| 
No



 a| 
límite
 a| 
El número máximo de objetos iniciador que se van a devolver.
 a| 
entero
 a| 
(ilimitada)
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
iniciadores
 a| 
Lista de la información del iniciador.
 a| 
xref:reference_element_api_initiator.adoc[iniciador] cabina

|===


== Excepciones

Este método puede tener la siguiente excepción:

|===


| Nombre | Descripción 


 a| 
XInvalidParameter
 a| 
Emitido si incluye el startInitiatorID y los parámetros de iniciadores en la misma llamada de método.

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "ListInitiators",
   "params": {},
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "initiators": [
      {
        "alias": "",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:c84ffd71216",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Nuevo desde la versión

9.6
