---
permalink: api/reference_element_api_deletekeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,deleting,delete 
summary: 'Puede utilizar el método DeleteKeyServerKmip para eliminar un servidor existente de claves \(KMIP\) del Protocolo de interoperabilidad de gestión de claves. Puede eliminar un servidor de claves a menos que sea el último asignado a su proveedor, y ese proveedor proporciona claves que están en uso actualmente.' 
---
= DeleteKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `DeleteKeyServerKmip` Método para eliminar un servidor de claves de protocolo de interoperabilidad de gestión de claves (KMIP) existente. Puede eliminar un servidor de claves a menos que sea el último asignado a su proveedor, y ese proveedor proporciona claves que están en uso actualmente.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
KeyServerID
 a| 
El ID del servidor de claves KMIP que se desea eliminar.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método tiene los valores no return. La operación de eliminación se considera correcta si no hay errores.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "DeleteKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== Nuevo desde la versión

11.7
