---
permalink: api/reference_element_api_getprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,retrieve protection domains 
summary: Puede utilizar el método GetProtectionDomainLayout para devolver toda la información del dominio de protección de un clúster, incluido el chasis y el dominio de protección personalizado en el que se encuentra cada nodo. 
---
= GetProtectionDomainLayout
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `GetProtectionDomainLayout` método para obtener toda la información del dominio de protección de un clúster, incluido el chasis y el dominio de protección personalizado en cada nodo.



== Parámetro

Este método tiene los parámetros no input.



== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
ProtectionDomainLayout
 a| 
Lista de nodos, cada uno con sus dominios de protección asociados.
 a| 
Lista JSON de link:reference_element_api_nodeprotectiondomains.md#GUID-3750B3B8-6A66-402F-85F1-E828005084BB["ProtectionDomains de nodo"] objetos.

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "GetProtectionDomainLayout",
  "params": {},
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== Nuevo desde la versión

12.0
