---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: Puede utilizar el método ModifyVirtualNetwork para cambiar los atributos de una red virtual existente. 
---
= ModificyVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ModifyVirtualNetwork` método para cambiar los atributos de una red virtual existente.

Este método permite agregar o quitar bloques de direcciones, cambiar la máscara de red o modificar el nombre o la descripción de la red virtual. También se puede utilizar para habilitar o deshabilitar espacios de nombres, así como para agregar o quitar una puerta de enlace si los espacios de nombres están habilitados en la red virtual.


NOTE: Este método requiere virtualNetworkID o virtualNetworkTag como parámetro, pero no ambos.

PRECAUCIÓN:

Habilitar o deshabilitar la funcionalidad VLAN de almacenamiento enrutable para una red virtual existente cambiando el parámetro Namespace interrumpe cualquier tráfico gestionado por la red virtual. Lo mejor es cambiar el parámetro Namespace durante una ventana de mantenimiento programada.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===


| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
Cód. Virtual
 a| 
Identificador único de la red virtual que se va a modificar. Este es el ID de red virtual que asigna el clúster.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
VirtualNetworkTag
 a| 
La etiqueta de red que identifica la red virtual que se desea modificar.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
Bloqueos de direcciones
 a| 
El nuevo bloque de direcciones que se debe establecer para esta red virtual. Esto puede incluir nuevos bloques de direcciones para añadir al objeto existente o omitir los bloques de direcciones no utilizados que se deban eliminar. También puede ampliar o reducir el tamaño de los bloques de direcciones existentes. Sólo puede aumentar el tamaño de los bloqueos de direcciones iniciales de un objeto de red virtual; nunca puede reducirlo. Miembros requeridos para este objeto:

* Start: El inicio del rango de direcciones IP. (cadena)
* Size: El número de direcciones IP que se van a incluir en el bloque. (entero)

 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
puerta de enlace
 a| 
La dirección IP de una puerta de enlace de la red virtual. Este parámetro solo es válido si el parámetro Namespace está configurado en TRUE.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
atributos
 a| 
La lista de pares nombre-valor en el formato de objetos JSON.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
nombre
 a| 
El nuevo nombre de la red virtual.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
espacio de nombres
 a| 
Cuando se establece en true, habilita la funcionalidad VLAN de almacenamiento enrutable volviendo a la red virtual y configurando un espacio de nombres para que la contenga. Cuando se establece en false, se deshabilita la funcionalidad VRF para la red virtual. Si se cambia este valor, se interrumpe el tráfico que funciona con esta red virtual.
 a| 
booleano
 a| 
Ninguno
 a| 
No



 a| 
máscara de red
 a| 
Nueva máscara de red para esta red virtual.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
svip
 a| 
La dirección IP virtual de almacenamiento para esta red virtual. La SVIP para una red virtual no se puede modificar. Debe crear una red virtual nueva para usar una dirección SVIP diferente.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valores devueltos

Este método no tiene valores devueltos.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== Nuevo desde la versión

9.6
