---
permalink: api/reference_element_api_updateidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,update 
summary: Puede usar el método UpdateIdpConfiguration para actualizar una configuración existente con un IDP de terceros para el clúster. 
---
= UpdateIdpConfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `UpdateIdpConfiguration` Método para actualizar una configuración existente con un IDP de terceros para el clúster.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
GenerateNewCertificate
 a| 
Cuando se especifica como TRUE, se genera una clave SAML y un certificado nuevos y reemplaza la pareja existente. Nota: La sustitución del certificado existente interrumpirá la confianza establecida entre el clúster y el IDP hasta que se vuelvan a cargar los metadatos del proveedor de servicios del clúster en el IDP. Si no se proporciona o se establece en FALSE, el certificado y la clave SAML siguen sin cambios.
 a| 
booleano
 a| 
Ninguno
 a| 
No



 a| 
IdpConfigurationID
 a| 
UUID para la configuración de IDP de terceros.
 a| 
UUID
 a| 
Ninguno
 a| 
No



 a| 
IdpMetadata
 a| 
Metadatos IDP para los detalles de configuración e integración para el inicio de sesión único SAML 2.0.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
IdpName
 a| 
Nombre utilizado para identificar y recuperar un proveedor de IDP para el inicio de sesión único SAML 2.0.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
NewIdpName
 a| 
Si se especifica, este nombre sustituye el nombre del IDP anterior.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valores devueltos

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
IdpConfigInfo
 a| 
Información sobre la configuración de IDP de terceros.
 a| 
link:reference_element_api_idpconfiginfo.html["IdpConfigInfo"]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
"method": "UpdateIdpConfiguration",
"params": {
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "generateNewCertificate": true
    }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Nuevo desde la versión

12.0
