---
permalink: api/reference_element_api_checkpingonvlan.html 
sidebar: sidebar 
keywords: VLAN,pre-deployment,network,validation,validate,validating,check,checking,CheckPingOnVlan 
summary: Se puede utilizar el método CheckPingOnVlan para probar la conectividad de red en una VLAN temporal al realizar la validación de red previa a la implementación. CheckPingOnVlan crea una interfaz VLAN temporal, envía paquetes ICMP a todos los nodos del clúster de almacenamiento mediante la interfaz VLAN y quita la interfaz. 
---
= CheckPingOnVlan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `CheckPingOnVlan` Método para probar la conectividad de red en una VLAN temporal al realizar la validación de red previa a la implementación. `CheckPingOnVlan` Crea una interfaz de VLAN temporal, envía paquetes ICMP a todos los nodos del clúster de almacenamiento mediante la interfaz de VLAN y, a continuación, elimina la interfaz.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
intentos
 a| 
Especifica el número de veces que el sistema debe repetir el ping de prueba.
 a| 
entero
 a| 
5
 a| 
No



 a| 
hosts
 a| 
Especifica una lista separada por comas de direcciones o nombres de host de dispositivos para hacer ping.
 a| 
cadena
 a| 
Los nodos del clúster
 a| 
No



 a| 
interfaz
 a| 
La interfaz existente (base) desde la que se deben enviar los pings. Los posibles valores son los siguientes:

* Bond10G: Envíe ping desde la interfaz de Bond10G.
* Bond1G: Envíe ping desde la interfaz de Bond1G.

 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
Tamaño del paquete
 a| 
Especifica el número de bytes que se enviarán en el paquete ICMP que se envía a cada IP. El número de bytes debe ser inferior al MTU máximo especificado en la configuración de red.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
PingTimeoutMsec
 a| 
Especifica el número de milisegundos que se deben esperar por cada respuesta ping individual.
 a| 
entero
 a| 
500 ms
 a| 
No



 a| 
ProhibiitFragmentación
 a| 
Activa el indicador DF (no fragment) para los paquetes ICMP.
 a| 
booleano
 a| 
falso
 a| 
No



 a| 
SourceAddressV4
 a| 
La dirección IPv4 de origen que se va a usar en los paquetes ping ICMP.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
SourceAddressV6
 a| 
La dirección IPv6 de origen que se va a usar en los paquetes ping ICMP.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
TotalTimeoutSec
 a| 
Especifica el tiempo en segundos que el ping debe esperar a que se produzca una respuesta del sistema antes de emitir el siguiente intento de ping o de finalizar el proceso.
 a| 
entero
 a| 
5
 a| 
No



 a| 
VirtualNetworkTag
 a| 
El identificador de VLAN que se va a utilizar al enviar los paquetes ping.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===


| Nombre | Descripción | Tipo 


 a| 
resultado
 a| 
Lista de cada IP con la que el nodo pudo comunicarse y las estadísticas de respuesta ping.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
    "method": "CheckPingOnVlan",
    "params": {
        "interface": "Bond10G",
        "virtualNetworkTag": 4001,
        "sourceAddressV4": "192.168.41.4",
        "hosts": "192.168.41.2"
},
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "192.168.41.2": {
      "individualResponseCodes": [
        "Success",
        "Success",
        "Success",
        "Success",
        "Success"
      ],
      "individualResponseTimes": [
        "00:00:00.000373",
        "00:00:00.000098",
        "00:00:00.000097",
        "00:00:00.000074",
        "00:00:00.000075"
      ],
      "individualStatus": [
        true,
        true,
        true,
        true,
        true
      ],
      "interface": "Bond10G",
      "responseTime": "00:00:00.000143",
      "sourceAddressV4": "192.168.41.4",
      "successful": true,
      "virtualNetworkTag": 4001
    }
  }
}
----


== Nuevo desde la versión

11.1
