---
permalink: api/reference_element_api_getkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,getting information,retrieving 
summary: 'Puede utilizar el método GetKeyServerKmip para obtener información acerca del servidor de claves \(KMIP\) de Protocolo de interoperabilidad de gestión de claves especificado.' 
---
= GetKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `GetKeyServerKmip` Método para obtener información sobre el servidor de claves de protocolo de interoperabilidad de gestión de claves (KMIP) especificado.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
KeyServerID
 a| 
El ID del servidor de claves KMIP acerca de la cual se desea obtener información.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===
| Nombre | Descripción | Tipo 


 a| 
KmipKeyServer
 a| 
Objeto que contiene detalles acerca del servidor de claves solicitado.
 a| 
link:reference_element_api_keyserverkmip.md#["KeyServerKmip"]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "GetKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":15
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nuevo desde la versión

11.7
