---
permalink: api/reference_element_api_listvirtualnetworks.html 
sidebar: sidebar 
keywords: virtual,network,networks,listing,list,listvirtualnetworks 
summary: Puede utilizar el método ListVirtualNetworks para enumerar todas las redes virtuales configuradas para el clúster. 
---
= ListVirtualNetworks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListVirtualNetworks` método para enumerar todas las redes virtuales configuradas para el clúster.

Puede utilizar este método para comprobar la configuración de red virtual en el clúster. No hay parámetros necesarios para este método. Sin embargo, para filtrar los resultados, puede pasar uno o más valores virtualNetworkID o virtualNetworkTag.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
Cód. Virtual
 a| 
ID de red para filtrar la lista de una sola red virtual.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
VirtualNetworkTag
 a| 
Etiqueta de red para filtrar la lista de una sola red virtual.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
VirtualNetworkIDs
 a| 
ID de red que se incluirán en la lista.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
No



 a| 
VirtualNetworkTags
 a| 
Etiqueta de red que se incluirá en la lista.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
Redes de virtualización
 a| 
Objeto que contiene direcciones IP de red virtual.
 a| 
xref:reference_element_api_virtualnetwork.adoc[VirtualNetwork]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "ListVirtualNetworks",
  "params": {
     "virtualNetworkIDs": [5,6]
   },
"id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "virtualNetworks": [
   {
    "addressBlocks": [
   {
    "available": "11000000",
    "size": 8,
    "start": "10.26.250.207"
   }
 ],
    "attributes": null,
    "gateway": "10.26.250.254",
    "name": "2250",
    "namespace": false,
    "netmask": "255.255.255.0",
    "svip": "10.26.250.200",
    "virtualNetworkID": 2250
   },
   {
     "addressBlocks": [
   {
     "available": "11000000",
     "size": 8,
     "start": "10.26.241.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.241.254",
     "name": "2241",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.241.200",
     "virtualNetworkID": 2241
   },
  {
     "addressBlocks": [
  {
     "available": "11000000",
     "size": 8,
     "start": "10.26.240.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.240.254",
     "name": "2240",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.240.200",
     "virtualNetworkID": 2240
    },
   {
  }
 ]
}
----


== Nuevo desde la versión

9.6
