---
permalink: api/reference_element_api_startbulkvolumeread.html 
sidebar: sidebar 
keywords: volume,read,session,start,starting,bulk,startbulkvolumeread 
summary: Se puede utilizar el método StartBulkVolumeRead para iniciar una sesión de lectura de volumen masivo en un volumen especificado. 
---
= StartBulkVolumeRead
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `StartBulkVolumeRead` método para iniciar una sesión de lectura masiva de volúmenes en un volumen especificado.

Solo se pueden ejecutar simultáneamente dos procesos de volúmenes masivos en un volumen. Cuando se inicializa la sesión, se leen datos de un volumen de almacenamiento de SolidFire que se almacena en un origen de backup externo. Un servidor web que se ejecuta en un nodo de almacenamiento de Element, accede a los datos externos. La información de interacción del servidor para el acceso a datos externos es pasada por un script que se ejecuta en el sistema de almacenamiento.

Al inicio de una operación de lectura masiva de volúmenes, se realiza una copia de Snapshot del volumen y la copia de Snapshot se elimina cuando finaliza la lectura. También es posible leer una copia de Snapshot del volumen si se introduce el ID de la copia de Snapshot como un parámetro. Cuando se lee una snapshot anterior, el sistema no crea una snapshot nueva del volumen ni elimina la snapshot anterior cuando finaliza la lectura.


NOTE: Este proceso crea una nueva snapshot si no se proporciona el ID de una snapshot existente. Se pueden crear copias de Snapshot si la ocupación del clúster se encuentra en la etapa 2 o 3. Las copias de Snapshot no se crean cuando la ocupación del clúster se encuentra en la etapa 4 o 5.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
formato
 a| 
El formato de los datos del volumen. Puede ser:

* `uncompressed`: Todos los bytes del volumen se devuelven sin compresión.
* `native`: Los datos Opaque se devuelven que son más pequeños y eficientes almacenados y escritos en una escritura masiva posterior.

 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
ID de volumen
 a| 
El ID del volumen que se leerá.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
ID de copia Snapshot
 a| 
El ID de una snapshot creada previamente para lecturas de volúmenes masivos. Si no se introduce ningún ID, se realiza una snapshot de la imagen de volumen activo actual.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
guión
 a| 
El nombre de un script ejecutable. Si no se otorga ningún nombre de script, la clave y la URL son necesarias para acceder a los nodos de almacenamiento Element. La secuencia de comandos se ejecuta en el nodo primario, y la clave y la URL se devuelven al script para que se pueda contactar con el servidor web local.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
ScriptParameters
 a| 
Parámetros JSON para pasar al script.
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No



 a| 
atributos
 a| 
La lista de pares nombre-valor en el formato de objetos JSON. link:reference_element_api_attributes.html["Leer más"].
 a| 
Objeto JSON
 a| 
Ninguno
 a| 
No

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===


| Nombre | Descripción | Tipo 


 a| 
Establish asyncHandle
 a| 
El ID del proceso asíncrono que se comprobará para que finalice.
 a| 
entero



 a| 
clave
 a| 
Clave opaca que identifica de forma exclusiva la sesión.
 a| 
cadena



 a| 
url
 a| 
URL para acceder al servidor web del nodo.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "StartBulkVolumeRead",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
      "snapshotID" : 2
   },
   "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
      "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== Nuevo desde la versión

9.6
