---
permalink: api/reference_element_api_setlicensekey.html 
sidebar: sidebar 
keywords: set,setting,license,key 
summary: En los clústeres de almacenamiento de SDS empresarial de SolidFire, puede utilizar el método SetLicenseKey para establecer la clave de licencia del clúster de almacenamiento. La clave de licencia de un clúster de almacenamiento consta del número de orden del clúster combinado con el número de serie y activa el modelo de capacidad que se compró para el software Element. 
---
= SetLicenseKey
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En los clústeres de almacenamiento de SDS empresarial de SolidFire, puede utilizar el `SetLicenseKey` método para establecer la clave de licencia para el clúster de almacenamiento. La clave de licencia de un clúster de almacenamiento consta del número de orden del clúster combinado con el número de serie y activa el modelo de capacidad que se compró para el software Element.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
Número de pedido
 a| 
El nuevo número de pedido de ventas para este clúster de almacenamiento.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí



 a| 
SerialNumber
 a| 
El nuevo número de serie para este clúster de almacenamiento.
 a| 
cadena
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===
| Nombre | Descripción | Tipo 


 a| 
Número de pedido
 a| 
El nuevo número de pedido de ventas del clúster de almacenamiento.
 a| 
cadena



 a| 
SerialNumber
 a| 
El nuevo número de serie del clúster de almacenamiento.
 a| 
cadena

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "SetLicenseKey",
  "params": {
    "orderNumber": "33601",
    "serialNumber": "30G56E3WV"   },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id" : 1,
   "result" : {
      "serialNumber": "30G56E3WV",
      "orderNumber": "33601"
     }
   }
}
----


== Nuevo desde la versión

12.2
