---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: Puede usar el método GetRemoteLoggingHosts para obtener la lista actual de servidores de registro. 
---
= GetRemoteLoggingHosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `GetRemoteLoggingHosts` método para obtener la lista actual de servidores de registro.



== Parámetros

No hay parámetros de entrada para `GetRemoteLoggingHosts` .



== Valor de retorno

El `GetRemoteLoggingHosts` Este método tiene el siguiente valor de retorno:

|===
| Nombre | Descripción | Tipo 


 a| 
RemoteHosts
 a| 
Enumera la dirección IP, el FQDN y la información del puerto de los hosts configurados para recibir información de registro reenviada.
 a| 
xref:reference_element_api_loggingserver.adoc[LoggingServer] cabina

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         },
         {
            "host": "syslogs.lab.company.net",
            "port": 514
         }
      ]
   }
}
----


== Nuevo desde la versión

Disponible a partir de ONTAP 9.6.



== Obtenga más información

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingHosts]
