---
permalink: api/reference_element_api_modifysnapmirrorrelationship.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,relationship,modifysnapmirrorrelationship 
summary: Puede utilizar ModifiySnapMirrorRelationship para cambiar los intervalos en los que se produce una instantánea programada. También puede eliminar o pausar una programación mediante este método. 
---
= ModificySnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar `ModifySnapMirrorRelationship` cambiar los intervalos en los que se produce una snapshot programada. También puede eliminar o pausar una programación mediante este método.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===


| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
DestationVolume
 a| 
El volumen de destino de la relación de SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeinfo]
 a| 
Ninguno
 a| 
Sí



 a| 
MaxTransferRate
 a| 
Especifica la tasa máxima de transferencia de datos entre los volúmenes en kilobytes por segundo. El valor predeterminado, 0, es ilimitado y permite que la relación de SnapMirror utilice completamente el ancho de banda de red disponible.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
PolicyName
 a| 
Especifica el nombre de la política de SnapMirror de ONTAP para la relación.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
Nombre de la pila
 a| 
El nombre de la programación cron preexistente del sistema ONTAP que se utiliza para actualizar la relación SnapMirror.
 a| 
cadena
 a| 
Ninguno
 a| 
No



 a| 
SnapMirrorEndpointID
 a| 
El ID de extremo del sistema de almacenamiento remoto de ONTAP se comunica con el clúster de almacenamiento de Element.
 a| 
entero
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
SnapMirrorRelationship
 a| 
Objeto que contiene los atributos de relación de SnapMirror modificados.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Nuevo desde la versión

10.1
