---
permalink: api/reference_element_api_listactivepairedvolumes.html 
sidebar: sidebar 
keywords: active,pairs,paired,pair,volume,volumes,list,listing,listactivepairedvolumes 
summary: Puede utilizar el método ListActivePairedVolumes para enumerar todos los volúmenes activos emparejados con un volumen. Este método muestra información acerca de los volúmenes con emparejamientos activos y pendientes. 
---
= ListActivePairedVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListActivePairedVolumes` método para enumerar todos los volúmenes activos emparejados con un volumen. Este método muestra información acerca de los volúmenes con emparejamientos activos y pendientes.



== Parámetros

Este método no tiene parámetros de entrada.



== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
volúmenes
 a| 
Información de volumen de los volúmenes emparejados.
 a| 
xref:reference_element_api_volumepair.adoc[Pareja de volúmenes] cabina

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "ListActivePairedVolumes",
   "params": {
      },
   "id" : 1
}
----


== Ejemplo de respuesta

Las respuestas para este método son similares al ejemplo siguiente:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-06-24T15:21:59Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:0oto.bk.24",
                "name": "BK",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000018f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000018",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 10737418240,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 24,
                "volumePairs": [
                    {
                        "clusterPairID": 2,
                        "remoteReplication": {
                            "mode": "Async",
                            "pauseLimit": 3145728000,
                            "remoteServiceID": 14,
                            "resumeDetails": "",
                            "snapshotReplication": {
                                "state": "Idle",
                                "stateDetails": ""
                            },
                            "state": "Active",
                            "stateDetails": ""
                        },
                        "remoteSliceID": 8,
                        "remoteVolumeID": 8,
                        "remoteVolumeName": "PairingDoc",
                        "volumePairUUID": "229fcbf3-2d35-4625-865a-d04bb9455cef"
                    }
                ]
            }
        ]
    }
}
----


== Nuevo desde la versión

9.6
