---
permalink: api/reference_element_api_listsnapmirrorschedules.html 
sidebar: sidebar 
keywords: snapmirror,schedule,schedules,list,listing,listsnapmirrorschedules,ontap 
summary: La interfaz de usuario web del software Element utiliza el método ListSnapMirrorSchedules para obtener una lista de las programaciones disponibles en un clúster de ONTAP remoto. 
---
= ListSnapMirrorSchedules
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario web del software Element utiliza el `ListSnapMirrorSchedules` Método para obtener una lista de las programaciones disponibles en un clúster de ONTAP remoto.



== Parámetro

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
SnapMirrorEndpointID
 a| 
Si se proporciona, el sistema enumera las programaciones del extremo con el identificador de extremo de SnapMirror especificado. Si no se proporciona esta opción, el sistema enumera las programaciones de todos los extremos de SnapMirror conocidos.
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
SnapMirrorSchedules
 a| 
Una lista de las programaciones de SnapMirror en el clúster de ONTAP remoto.
 a| 
xref:reference_element_api_snapmirrorjobschedulecroninfo.adoc[SnapMirrorJobScheduleCronInfo] cabina

|===


== Nuevo desde la versión

10.1
