---
permalink: api/reference_element_api_modifyclusterfullthreshold.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,cluster,full,fullness,threshold,modifyclusterfullthreshold 
summary: Puede utilizar el método ModifyClusterFullThreshold para cambiar el nivel en el que el sistema genera un evento cuando el clúster de almacenamiento se acerca a una determinada utilización de la capacidad. La configuración de umbral se puede utilizar para indicar la cantidad aceptable de almacenamiento en bloques utilizado antes de que el sistema genere una advertencia. 
---
= ModifyClusterFullThreshold
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ModifyClusterFullThreshold` método para cambiar el nivel en el que el sistema genera un evento cuando el clúster de almacenamiento se acerca a un determinado uso de la capacidad. La configuración de umbral se puede utilizar para indicar la cantidad aceptable de almacenamiento en bloques utilizado antes de que el sistema genere una advertencia.

Por ejemplo, si desea recibir una alerta cuando el sistema alcance un 3 % por debajo del uso de almacenamiento en bloque de nivel "error", introduzca el valor "3" para el parámetro stage3BlockThreholdPercent. Si se alcanza este nivel, el sistema envía una alerta al registro de eventos en la Consola de administración de clústeres.



== Parámetros

Este método tiene los siguientes parámetros de entrada:


NOTE: Debe seleccionar al menos un parámetro.

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
MaxMetadataOverProvisionFactor
 a| 
Un representante de valor del número de veces que el espacio de metadatos se puede aprovisionar en exceso en relación con la cantidad de espacio disponible. Por ejemplo, si había suficiente espacio de metadatos para almacenar 100 TIB de volúmenes y este número se estableció en 5, se podría crear un valor de 500 TIB de volúmenes.
 a| 
entero
 a| 
5
 a| 
No



 a| 
Stage2AwareThreshold
 a| 
El número de nodos de capacidad que queda en el clúster antes de que el sistema active una notificación de capacidad.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
Stage3BlockThresholdPercent
 a| 
El porcentaje de uso del almacenamiento en bloque es inferior al umbral "error" que hace que el sistema active una alerta de "advertencia" de clúster.
 a| 
entero
 a| 
Ninguno
 a| 
No



 a| 
Stage3MetadataThresholdPercent
 a| 
El porcentaje de utilización del almacenamiento de metadatos por debajo del umbral "'error'" que hace que el sistema active una alerta de clúster "'Advertencia'".
 a| 
entero
 a| 
Ninguno
 a| 
No

|===


== Valores devueltos

Este método tiene los siguientes valores devueltos:

|===


| Nombre | Descripción | Tipo 


 a| 
BlockFullness
 a| 
El nivel calculado actual de ocupación del bloque del clúster.

* Stage1Happy: Sin alertas ni condiciones de error. Corresponde al estado *saludable* de la interfaz de usuario web.
* Stage2Aware: Sin alertas ni condiciones de error. Corresponde al estado *saludable* de la interfaz de usuario web.
* Stage3Low: El sistema no puede brindar protección de datos redundante contra dos fallos de nodo sin simultáneo. Corresponde al estado *Warning* de la interfaz de usuario web. Es posible configurar este nivel en la interfaz de usuario web (el sistema activa esta alerta de forma predeterminada cuando la capacidad es un 3 % inferior al estado error).
* Stage4Critical: El sistema no es capaz de brindar protección de datos redundante desde un fallo de nodo único. No se pueden crear volúmenes o clones nuevos. Corresponde al estado *error* en la interfaz de usuario del elemento.
* Stage5CompletelyConsumed: Totalmente consumido. El clúster es de solo lectura; se mantienen las conexiones iSCSI, pero se suspenden todas las escrituras. Corresponde al estado *Critical* de la interfaz de usuario de elemento.

 a| 
cadena



 a| 
plenitud
 a| 
Refleja el nivel más alto de plenitud entre "blockFullness" y "metadataFullness".
 a| 
cadena



 a| 
MaxMetadataOverProvisionFactor
 a| 
Un representante de valor del número de veces que el espacio de metadatos se puede aprovisionar en exceso en relación con la cantidad de espacio disponible. Por ejemplo, si había suficiente espacio de metadatos para almacenar 100 TIB de volúmenes y este número se estableció en 5, se podría crear un valor de 500 TIB de volúmenes.
 a| 
entero



 a| 
MetadataFullness
 a| 
El nivel calculado actual de ocupación de metadatos del clúster.

* Stage1Happy: Sin alertas ni condiciones de error. Corresponde al estado *saludable* de la interfaz de usuario web.
* Stage2Aware: Sin alertas ni condiciones de error. Corresponde al estado *saludable* de la interfaz de usuario web.
* Stage3Low: El sistema no puede brindar protección de datos redundante contra dos fallos de nodo sin simultáneo. Corresponde al estado *Warning* de la interfaz de usuario web. Es posible configurar este nivel en la interfaz de usuario web (el sistema activa esta alerta de forma predeterminada cuando la capacidad es un 3 % inferior al estado error).
* Stage4Critical: El sistema no es capaz de brindar protección de datos redundante desde un fallo de nodo único. No se pueden crear volúmenes o clones nuevos. Corresponde al estado *error* en la interfaz de usuario del elemento.
* Stage5CompletelyConsumed: Totalmente consumido. El clúster es de solo lectura; se mantienen las conexiones iSCSI, pero se suspenden todas las escrituras. Corresponde al estado *Critical* de la interfaz de usuario de elemento.

 a| 
cadena



 a| 
SliceReserveUsedThresholdPct
 a| 
Condición de error. Se activa una alerta del sistema si el uso del segmento de umbral reservado es mayor que el valor devuelto por sliceReserveUsedholdPct .
 a| 
entero



 a| 
Stage2AwareThreshold
 a| 
Condición de conciencia. El valor que se establece para el nivel de umbral del clúster "fase 2".
 a| 
entero



 a| 
Stage2BlockThresholdBytes
 a| 
El número de bytes que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 2.
 a| 
entero



 a| 
Stage2MetadataThresholdBytes
 a| 
El número de bytes de metadatos que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 2.
 a| 



 a| 
Stage3BlockThresholdBytes
 a| 
El número de bytes de almacenamiento que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 3.
 a| 
entero



 a| 
Stage3BlockThresholdPercent
 a| 
El valor porcentual establecido para la etapa 3. En este porcentaje lleno, se publica una advertencia en el registro de alertas.
 a| 
entero



 a| 
Stage3LowThreshold
 a| 
Condición de error. El umbral en el que se crea una alerta del sistema debido a la baja capacidad de un clúster.
 a| 
entero



 a| 
Stage3MetadataThresholdBytes
 a| 
El número de bytes de metadatos que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 3.
 a| 



 a| 
Stage4BlockThresholdBytes
 a| 
El número de bytes de almacenamiento que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 4.
 a| 
entero



 a| 
Stage4Critical Threshold
 a| 
Condición de error. El umbral en el que se crea una alerta del sistema para informar sobre una capacidad extremadamente baja en un clúster.
 a| 
entero



 a| 
Stage4MetadataThresholdBytes
 a| 
El número de bytes de metadatos que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 4.
 a| 



 a| 
Stage5BlockThresholdBytes
 a| 
El número de bytes de almacenamiento que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 5.
 a| 
entero



 a| 
Stage5MetadataThresholdBytes
 a| 
El número de bytes de metadatos que utiliza el clúster en el cual existirá una condición de ocupación de la etapa 5.
 a| 



 a| 
SumTotalClusterBytes
 a| 
La capacidad física del clúster, medida en bytes.
 a| 
entero



 a| 
SumTotalMetadataClusterBytes
 a| 
La cantidad total de espacio que se puede utilizar para almacenar metadatos.
 a| 
entero



 a| 
SumUsedClusterBytes
 a| 
La cantidad de bytes de almacenamiento que se utiliza en el clúster.
 a| 
entero



 a| 
SUUsedMetadataClusterBytes
 a| 
La cantidad de espacio usado en las unidades de volúmenes para almacenar metadatos.
 a| 
entero

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method" : "ModifyClusterFullThreshold",
   "params" : {
              "stage3BlockThresholdPercent" : 3
              },
   "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "blockFullness": "stage1Happy",
    "fullness": "stage3Low",
    "maxMetadataOverProvisionFactor": 5,
    "metadataFullness": "stage3Low",
    "sliceReserveUsedThresholdPct": 5,
    "stage2AwareThreshold": 3,
    "stage2BlockThresholdBytes": 2640607661261,
    "stage3BlockThresholdBytes": 8281905846682,
    "stage3BlockThresholdPercent": 3,
    "stage3LowThreshold": 2,
    "stage4BlockThresholdBytes": 8641988709581,
    "stage4CriticalThreshold": 1,
    "stage5BlockThresholdBytes": 12002762096640,
    "sumTotalClusterBytes": 12002762096640,
    "sumTotalMetadataClusterBytes": 404849531289,
    "sumUsedClusterBytes": 45553617581,
    "sumUsedMetadataClusterBytes": 31703113728
  }
}
----


== Nuevo desde la versión

9.6
