---
permalink: api/reference_element_api_resumesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: ResumeSnapMirrorRelationship,resume,SnapMirror,relationship,resuming 
summary: La interfaz de usuario web del software Element utiliza el método ResumeSnapRelationship para permitir futuras transferencias de una relación de SnapMirror en modo inactivo. 
---
= ReumeSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de usuario web del software Element utiliza el `ResumeSnapMirrorRelationship` Método para habilitar futuras transferencias para una relación de SnapMirror en modo inactivo.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
SnapMirrorEndpointID
 a| 
El ID de extremo del sistema de almacenamiento remoto de ONTAP se comunica con el clúster de almacenamiento de Element.
 a| 
entero
 a| 
Ninguno
 a| 
Sí



 a| 
DestationVolume
 a| 
El volumen de destino de la relación de SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeinfo]
 a| 
Ninguno
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
SnapMirrorRelationship
 a| 
Objeto que contiene información acerca de la relación reanudada de SnapMirror.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Nuevo desde la versión

10.1
