---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: Puede utilizar el método DisableClusterSsh para deshabilitar el servicio SSH para todo el clúster de almacenamiento. Cuando añada nodos al clúster de almacenamiento, los nuevos nodos heredan esta configuración en todo el clúster. 
---
= DisableClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `DisableClusterSsh` Método para deshabilitar el servicio SSH para todo el clúster de almacenamiento. Cuando añada nodos al clúster de almacenamiento, los nuevos nodos heredan esta configuración en todo el clúster.


NOTE: El SDS empresarial de SolidFire no admite este método. Si utiliza este método en un sistema SolidFire eSDS, el método devolverá un error.



== Parámetro

Este método no tiene parámetro de entrada.



== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
resultado
 a| 
Un objeto JSON que contiene el estado del servicio SSH para el clúster de almacenamiento, el tiempo restante hasta que SSH esté deshabilitado y el estado del servicio SSH para cada nodo.
 a| 
Objeto JSON

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Nuevo desde la versión

10.3
