---
permalink: api/reference_element_api_clusterconfig.html 
sidebar: sidebar 
keywords: objects,object,clusterConfig 
summary: El objeto ClusterConfig muestra información que el nodo utiliza para comunicarse con el clúster. 
---
= ClusterConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `clusterConfig` object muestra información que el nodo utiliza para comunicarse con el clúster.



== Miembros de objeto

Este objeto contiene los siguientes miembros:

|===
| Nombre | Descripción | Tipo 


 a| 
`cipi`
 a| 
La interfaz de red que se utiliza para la comunicación del clúster.
 a| 
cadena



 a| 
`cluster`
 a| 
El nombre único del clúster.
 a| 
cadena



 a| 
`encryptionCapable`
 a| 
Especifica si el nodo admite cifrado.
 a| 
booleano



 a| 
`ensemble`
 a| 
Los nodos que participan en el clúster.
 a| 
matriz de cadenas



 a| 
`fipsDriveConfiguration`
 a| 
Especifica si el nodo es compatible con unidades certificadas con FIPS 140-2.
 a| 
booleano



 a| 
`hasLocalAdmin`
 a| 
Especifica si el clúster tiene un administrador local.
 a| 
booleano



 a| 
`mipi`
 a| 
La interfaz de red utilizada para la gestión de nodos.
 a| 
cadena



 a| 
`name`
 a| 
Identificador único del clúster.
 a| 
cadena



 a| 
`nodeID`
 a| 
Identificador único del nodo.
 a| 
entero



 a| 
`pendingNodeID`
 a| 
Identificador único del nodo pendiente.
 a| 
entero



 a| 
`role`
 a| 
Identifica el rol del nodo.
 a| 
cadena



 a| 
`sipi`
 a| 
La interfaz de red que se utiliza para el almacenamiento.
 a| 
cadena



 a| 
`state`
 a| 
Indica el estado del nodo.
 a| 
cadena



 a| 
`version`
 a| 
Indica la versión del nodo.
 a| 
cadena

|===