---
permalink: api/reference_element_api_deleteidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,delete 
summary: Puede utilizar el método DeleteIdpConfiguration para eliminar una configuración existente de un IDP de terceros para el clúster. Al eliminar la última configuración de IDP, se quita el certificado de proveedor de servicios SAML del clúster. 
---
= DeleteIdpConfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `DeleteIdpConfiguration` Método para eliminar una configuración existente de un IDP de terceros para el clúster. Al eliminar la última configuración de IDP, se quita el certificado de proveedor de servicios SAML del clúster.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
IdpConfigurationID
 a| 
UUID para la configuración de IDP de terceros.
 a| 
UUID
 a| 
Ninguno
 a| 
No



 a| 
IdpName
 a| 
Nombre utilizado para identificar y recuperar un proveedor de IDP para el inicio de sesión único SAML 2.0.
 a| 
cadena
 a| 
Ninguno
 a| 
No

|===


== Valores devueltos

Este método no tiene valores devueltos.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "DeleteIdpConfiguration",
  "params": {
    "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
    "idpName": "https://provider.name.url.com"
  }
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "result":{}
}
----


== Nuevo desde la versión

12.0
