---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'Se puede usar el método DeleteStorageContainers para eliminar hasta 2000 contenedores de almacenamiento de volumen virtual \(VVol\) del sistema a la vez. Los contenedores de almacenamiento que se quitan no deben contener ningún VVol.' 
---
= DeleteStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `DeleteStorageContainers` Método para eliminar hasta 2000 contenedores de almacenamiento Virtual Volume (VVol) del sistema a la vez. Los contenedores de almacenamiento que se quitan no deben contener ningún VVol.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
ContenerID de almacenamiento
 a| 
Una lista de ID de los contenedores de almacenamiento que se van a eliminar. Puede especificar hasta 2000 ID en la lista.
 a| 
Cabina de UUID
 a| 
Ninguno
 a| 
Sí

|===


== Valores devueltos

Este método no tiene valores devueltos.



== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nuevo desde la versión

9.6
