---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: Puede utilizar el método SetSnmpInfo para configurar SNMP versión 2 y versión 3 en nodos de clúster. Los valores establecidos con esta interfaz se aplican a todos los nodos del clúster y los valores que se pasan reemplazan a todos los valores establecidos en cualquier llamada anterior a SetSnmpInfo. 
---
= SetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `SetSnmpInfo` Método para configurar las versiones 2 y 3 de SNMP en nodos de clúster. Los valores establecidos con esta interfaz se aplican a todos los nodos del clúster y los valores que se pasan reemplazan a todos los valores establecidos en cualquier llamada anterior a. `SetSnmpInfo`.



== Parámetros


NOTE: SetSnmpInfo queda obsoleto para las versiones 6.0 y posteriores de los elementos. Utilice la xref:reference_element_api_enablesnmp.adoc[EnableSnmp] y.. xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] en su lugar, los métodos.

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
redes
 a| 
Lista de redes y qué tipo de acceso tienen a los servidores SNMP que se ejecutan en los nodos del clúster. Consulte SNMP xref:reference_element_api_network_snmp.adoc[red] objeto para los posibles valores. Este parámetro solo es necesario para SNMP v2.
 a| 
xref:reference_element_api_network_snmp.adoc[red] cabina
 a| 
Ninguno
 a| 
No



 a| 
activado
 a| 
Si se establece en true, se habilita SNMP en cada nodo del clúster.
 a| 
booleano
 a| 
falso
 a| 
No



 a| 
SnmpV3Enabled
 a| 
Si se establece en true, SNMP v3 se habilita en cada nodo del clúster.
 a| 
booleano
 a| 
falso
 a| 
No



 a| 
UsmUsers
 a| 
Si SNMP v3 está habilitado, este valor se debe pasar en lugar del parámetro Networks. Este parámetro es necesario únicamente para SNMP v3.
 a| 
xref:reference_element_api_usmuser.adoc[UsumUsuario]
 a| 
Ninguno
 a| 
No

|===


== Valores devueltos

Este método no tiene valores devueltos.



== Ejemplo de solicitud con SNMP v3 habilitado

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== Ejemplo de solicitud con SNMP v2 habilitado

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== Nuevo desde la versión

9.6
