---
permalink: api/reference_element_api_listclusterfaults.html 
sidebar: sidebar 
keywords: cluster,list,listing,fault,faults,listclusterfaults,error,errors 
summary: Puede usar el método ListClusterFaults para enumerar información sobre los fallos detectados en el clúster. Con este método, puede enumerar tanto los fallos actuales como los que se han resuelto. El sistema almacena en caché los fallos cada 30 segundos. 
---
= ListClusterFaults
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListClusterFaults` método para enumerar información sobre cualquier error detectado en el clúster. Con este método, puede enumerar tanto los fallos actuales como los que se han resuelto. El sistema almacena en caché los fallos cada 30 segundos.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
Prácticas más eficaces
 a| 
Incluir fallos activados por una configuración del sistema no óptima. Los posibles valores son los siguientes:

* verdadero
* falso

 a| 
booleano
 a| 
Ninguno
 a| 
No



 a| 
Intachable
 a| 
Determina los tipos de fallos devueltos. Los posibles valores son los siguientes:

* Actual: Lista de fallos activos sin resolver.
* Resuelto: Lista de fallos detectados y resueltos con anterioridad.
* All: Enumera los fallos actuales y resueltos. El estado del fallo puede verse en el miembro "relativamente solucionado" del objeto de fallo.

 a| 
cadena
 a| 
todo
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
fallos
 a| 
Un objeto que describe los errores solicitados del clúster.
 a| 
xref:reference_element_api_fault.adoc[fallo]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "ListClusterFaults",
    "params": {
      "faultTypes": "current",
      "bestPractices": true
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "faults": [
      {
        "blocksUpgrade": false,
        "clusterFaultID": 3,
        "code": "driveAvailable",
        "data": null,
        "date": "2024-04-03T22:22:56.660275Z",
        "details": "Node ID 1 has 6 available drive(s).",
        "driveID": 0,
        "driveIDs": [],
        "externalSource": "",
        "networkInterface": "",
        "nodeHardwareFaultID": 0,
        "nodeID": 1,
        "resolved": true,
        "resolvedDate": "2024-04-03T22:24:54.598693Z",
        "serviceID": 0,
        "severity": "warning",
        "type": "drive"
      },
      {
        "clusterFaultID": 9,
        "code": "disconnectedClusterPair",
        "data": null,
        "date": "2016-04-26T20:40:08.736597Z",
        "details": "One of the clusters in a pair may have become misconfigured or disconnected.  Remove the local pairing and retry pairing the clusters. Disconnected Cluster Pairs: []. Misconfigured Cluster Pairs: [3]",
        "driveID": 0,
        "driveIDs": [],
        "nodeHardwareFaultID": 0,
        "nodeID": 0,
        "resolved": false,
        "resolvedDate": "",
        "serviceID": 0,
        "severity": "warning",
        "type": "cluster"
      }
    ]
  }
}
----


== Nuevo desde la versión

9.6
