---
permalink: api/reference_element_api_listvirtualvolumebindings.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,cluster,bound,protocol,endpoint,binding,bindings,list,listing,listvirtualvolumebindings 
summary: Puede utilizar el método ListVirtualVolumeBindings para obtener una lista de todos los volúmenes virtuales del clúster enlazados a extremos de protocolo. 
---
= ListVirtualVolumeBindings
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListVirtualVolumeBindings` método para obtener una lista de todos los volúmenes virtuales en el clúster enlazados con extremos de protocolo.



== Parámetros

Este método tiene el siguiente parámetro de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
VirtualVolumeBindingIDs
 a| 
Una lista de ID de vinculación de volúmenes virtuales de los cuales se puede recuperar información. Si omite este parámetro, el método muestra información acerca de todas las vinculaciones de volúmenes virtuales.
 a| 
matriz en números enteros
 a| 
Ninguno
 a| 
No

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===
| Nombre | Descripción | Tipo 


 a| 
vinculaciones
 a| 
Una lista de objetos que describen todos los volúmenes virtuales del clúster vinculados a los extremos de protocolo.
 a| 
xref:reference_element_api_binding_vvols.adoc[vinculación]

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
  "method": "ListVirtualVolumeBindings",
    "params": {
    },
    "id": 1
}
----


== Ejemplo de respuesta

Este método devuelve una respuesta similar al siguiente ejemplo:

[listing]
----
{
  "id": 1,
  "result": {
    "bindings": [
      {
        "protocolEndpointID": "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b",
        "protocolEndpointInBandID": "naa.6f47acc2000000016a67746700000000",
        "protocolEndpointType": "SCSI",
        "virtualVolumeBindingID": 177,
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeSecondaryID": "0xe200000000a6"
      }
    ]
  }
}
----


== Nuevo desde la versión

9.6
