---
permalink: api/reference_element_api_listvolumesforaccount.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,account,active,pending,deleted,listvolumesforaccount 
summary: 'Puede utilizar el método ListVolumesForAccount para mostrar los volúmenes activos y \(Pending\) eliminados de una cuenta.' 
---
= ListVolumesForAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `ListVolumesForAccount` método para enumerar los volúmenes activos y (pendientes) eliminados de una cuenta.



== Parámetros

Este método tiene los siguientes parámetros de entrada:

|===
| Nombre | Descripción | Tipo | Valor predeterminado | Obligatorio 


 a| 
IncludeVirtualVolumes
 a| 
De forma predeterminada, se incluyen los volúmenes virtuales en la respuesta. Para excluir volúmenes virtuales, se debe establecer en FALSE.
 a| 
booleano
 a| 
verdadero
 a| 
No



 a| 
ID de cuenta
 a| 
Se devuelven todos los volúmenes que son propiedad de este ID de cuenta.
 a| 
entero
 a| 
No
 a| 
Sí

|===


== Valor de retorno

Este método tiene el siguiente valor devuelto:

|===


| Nombre | Descripción | Tipo 


 a| 
volúmenes
 a| 
Lista de información de volumen.
 a| 
xref:reference_element_api_volume.adoc[volumen] cabina

|===


== Ejemplo de solicitud

Las solicitudes de este método son similares al ejemplo siguiente:

[listing]
----
{
   "method": "ListVolumesForAccount",
   "params": {
      "accountID"  : 1
   },
   "id" : 1
}
----


== Ejemplo de respuesta

Las respuestas para este método son similares al ejemplo siguiente:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2018-07-22T16:15:25Z",
                "deleteTime": "",
                "enable512e": false,
                "iqn": "iqn.2010-01.com.solidfire:0oto.test1.25",
                "name": "test1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "306f746f00000019f47acc0100000000",
                "scsiNAADeviceID": "6f47acc100000000306f746f00000019",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 1000341504,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 25,
                "volumePairs": []
            }
        ]
    }
}
----


== Nuevo desde la versión

9.6
